### ISSUE TITLE
DKK point cost issue.

### ISSUE THREAD

**Issue by hobodabobo** [BSData/wh40k#1000]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** In the Death Korps of Krieg file, the character Marshal Venner should be a flat 55 points. His wargear should be included in his points.

**Comment by Zeshi91** [comment]
Marshal Karis Venner should be 60 points and not 70. You have to pay for his wargear because he is listed under Death Korps of Krieg Units (does not include wargear).

But his Memento Mori is not listed under Wargear in his Datasheet and should not cost extra. Unless there is an FAQ for this. Iirc there is a similar case for one of the Eldar HQ units.

**Comment by alphalas** [comment]
The last FAQ seems to indicate that if it has a cost, you pay for it, wargear listed or no. Trust me, I want it to be free too
