### ISSUE TITLE
Lieutenant has an extra bolt pistol. 

### ISSUE THREAD

**Issue by SSSlippy** [BSData/wh40k#1038]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Aldran** [comment]
It should not be a bug. By the Codex Space Marines:
"[A lieutenant] is armed with a chainsword, a master-crafted boltgun, a bolt pistol, frag grenades and krak grenades."
The wargear options say:
"Any model may replace its master crafted boltgun with an item from the Pistols, Combi-weapons or Melee Weapons lists."

Since the unit can trade its boltgun for a bolt pistol, and it comes with a bolt pistol, it can have two such weapons. I do not know why someone would do that, but it is legal.

**Comment by SSSlippy** [comment]
The issue is if you try to give it 2 bolt pistols validation fails and says has to many selections of bolt pistol.
