### ISSUE TITLE
cant get any of these socalled data files to work in battlescribe

### ISSUE THREAD

**Issue by TRMBeefy** [BSData/wh40k#1056]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
every file i try to add to my data comes up as error out of date or does nothing... how the hell is this even supposed to work? im not a coder... i just want a simple download button that makes the fucking app work

**Comment by amis92** [comment]
I'm very sorry you have had such a bad experience it made you swear publicly. Please don't repeat the same mistake again in our repositories.

You didn't provide us any specific information so we cannot help you. Do you have newest version of BattleScribe? What platform are you using it on? Did you read README on repo's homepage? Did you try selecting wh40k in Manage Data view in BattleScribe? Can you give us any screenshots of the error? (You can drag-and-drop pictures into response here)

**Comment by skonk** [comment]
Considering you are the only person reporting this issue out of thousands of users, perhaps you are doing something not quite right?

The current version of BattleScribe is fully automated in terms of acquiring data for your chosen game.

On launching the app, it should present you with the option to add data which once clicked on, will give you a list of support game systems allowing you to tick Warhammer 40,000 and it will then download all the required data files for you.

**Comment by macfisher** [comment]
I know this issue is closed but I'd like to comment that when I opened the `Select Repositories` option the program opened a window that was too small to see the checkboxes. New users who do not know to expect to see checkboxes will not know to stretch the window out to be able to see them. Maybe allow the text to be selected as well? Thanks for the amazing software. Haven't had any other issues and I've been using this for about two years.
