### ISSUE TITLE
Imperium - SM Index options?

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#1067]
As stated here, the index entries for things not found in the SM codex are valid to be taken: https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/

Where in the data files do I find these now? Specifically I want to add a twin autocannon to my Veteran Dreadnoughts

**Comment by Drachnyen** [comment]
Hey, 

Since the datasheets in the codex replaces the ones from the index, I don't think it's an option anymore:

![img_2055](https://user-images.githubusercontent.com/16340056/28827598-19f4f15e-769c-11e7-8ed1-c660108d0809.PNG)

They clarified it a bit further in the link you provided : 

**Can I combine units from the index and a codex into one army?**
The datasheets in the new codexes overwrite the same datasheets in the index books. You can certainly use units with updated datasheets alongside units from the index that have yet to be updated. Once a unit has been covered in the codex though, we assume you’re using the latest version.

**Can I choose to use the rules and/or points for units from my index instead of the new ones in the codex once released?**
In your own games, if you and your opponent agree, you can, of course, play with whatever rules you like.

In all future publications and official events though, it will be assumed that you’re using the most recent rules and Datasheets. It will also be assumed that you’re using the most up to date points for matched play, in this case, those included in the codex.

**Comment by BaconCatBug** [comment]
**There are a few options that are missing in the codex that appear in the index: why is that? Does that mean I can’t use these models in my army anymore?**
While the indexes are designed to cover a long history of miniatures, the codexes are designed to give you rules for the current Warhammer 40,000 range. There are a few options in the indexes for some Characters and vehicles that are no longer represented in the Citadel range – _certain Dreadnought weapons that don’t come in the box,_ or some characters on bikes, for example.
Don’t worry though, _you can still use all of these in your games if you have these older models. In these instances, use the datasheet from the index, and the most recent points published for that model and its weapons_ (currently, also in the index).

They explicitly call out dreadnought weapons as something you can use the index for.

**Comment by Drachnyen** [comment]
Yeah they do mention Dreadnoughts specifically, except we have contradicting text in the same document!

"In all future publications and official events though, it will be assumed that you’re using the most recent rules and Datasheets. It will also be assumed that you’re using the most up to date points for matched play, in this case, those included in the codex."

This needs clarification as the two paragraphs contradict themselves

**Comment by flakpanda** [comment]
We are discussing this and working on it.

**Comment by flakpanda** [comment]
We have decided to be all inclusive and support all the options available to a datasheet henceforth.
