### ISSUE TITLE
Imperium - Death Korps of Krieg V16 - Need twin-linked Heavy stubber added

### ISSUE THREAD

**Issue by jShepherddog** [BSData/wh40k#1109]
**File/Catalogue:** 

**BattleScribe version:** Warhammer 40k v2.01.04    Death Korps of Krieg V16

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**1.**The entry for the Death Korps of Krieg Heavy Weapons Team has no option to add a twin-linked Heavy stubber, this was added to the index by the FAQ.
![image](https://user-images.githubusercontent.com/30080443/28974133-51cd662e-7903-11e7-887d-3421724c9317.png)

**2.** The Death Korps of Krieg Infantry Squad, There are no Frag or Krak grenades included with each trooper. They should all be equipped with these grenades automatically.

**Comment by CrusherJoe** [comment]
1. Yes the FAQ did indeed add the weapon choice, but what it did NOT add any other information on the "twin heavy stubber" -- particularly, a weapon profile or a points cost. I have looked over the wargear options in both Index Imperium 2 and IAI: Forces of the Astra Militarum and nowhere do I see a reference to a "twin heavy stubber", neither in terms of points or a weapon profile. I am far from infallible (and I really want to be wrong here), so if you could please point me to a reference source/page number for a points cost and weapon profile for the "twin heavy stubber" I'll be more than happy to include it in the DKOK catalog.
2. Oops, you're correct. Fixed in v17 of the catalog.

**Comment by CrusherJoe** [comment]
Oops I found the THS in the FAQ. D'oh. Adding it now.

**Comment by CrusherJoe** [comment]
Okay, now both issues reported are fixed in v17 of the DKOK cat.
