### ISSUE TITLE
Chaos - Chaos Space Marines: Chosen weapon validation issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1268]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.06

**Platform:** Android

**Dropbox:** No

**Description:** I am unable to give my chosen champion his equipment of a power Axe and a Combi Melta. And I am unable to give one of my chosen a pair of lightning claws.

**Comment by darkscion0** [comment]
Page 117 of the Codex under Champion Equipment. You can't run a power axe plus a combi melta. 

The champion can take two of the following:
Bolt Pistol
Chainaxe
Chainsword
Lightning Claw
Plasma Pistol
Power Axe
Power Fist
Power Maul
Power Sword

**OR one** from the following list:
Boltgun
Combi-bolter
Combi-flamer
Combi-melta
Combi-plasma

Chosen lightning claws is being fixed in v27.

**Comment by eewone** [comment]
Okay so the model of vrosh Tattersoul is pretty much useless now?

**Comment by ilaunchbury** [comment]
@eewone, Vrosh has his own datasheet, which is still valid. You just can't take him as a standard unit champion.

If I can track down the sheet, I'll add him in as himself.

The Lightning Claws issues is fixed in v27 of the CSM file, which will be in the next release.

**Comment by alphalas** [comment]
@eewone, what @ilaunchbury meant is you can't use the model as an AspChamp; but you can use it as a ExChamp (which is what Vrosh is in the DV update)

**Comment by ilaunchbury** [comment]
Yes, I forgot that the Exalted Champion gets the "HQ" weapon options which *do* allow him to be taken as is.
