### ISSUE TITLE
CSM Elites as troops for World Eaters and EC

### ISSUE THREAD

**Issue by JasonMWelch** [BSData/wh40k#1269]
Chaos Space Marines

**BattleScribe version:** 2.01.

**Platform:** iOS

**Dropbox**

Description:  World Eaters can no longer select Berzerkers as troops, same for Emperors Children and Noise marines.  These are still valid as the index Troop entries for them were not over ridden.  Can we get these back?

**Comment by ilaunchbury** [comment]
The Codex replaces the Index for units which are still sold and have no unavailable weapon options. Both Berzerkers and Noise Marines fall into this category. 

You no longer use the rules from the Index for World Eaters and Emperor's Children, because the Codex is now the valid rule set for those Legions. GW have never stated that you can choose to use **rules** from an Index instead of a Codex, only that datasheets for models which are no longer sold, or have weapon options that are no longer sold, can be used from an Index. There are no rules in the Codex which say those units are Troops.

Until and unless it gets an FAQ, those units are Elites.

**Comment by JasonMWelch** [comment]
FAQ is up, they are troops.
