### ISSUE TITLE
Debate about Sergeant loadout SM

### ISSUE THREAD

**Issue by Hellgore1974** [BSData/wh40k#1335]
**File/Catalogue:** Warhammer 40k; Codex Adeptus Astartes

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

It occurs to me that there is a debatable point of view about how many weapons a Tac-Sergeant can have when swapping in his BP and BG.
Wargear option says (quote): "The Space Marine Sergeant may replace bolt pistol and boltgun with **items** from the Sergeant Equipment list." Note that it says ITEMS, not one for each or anything. And then we have the Sergeant Equipment list section (again, quote):
"Up to **two** weapons can be chosen from the following list: Bolt pistol, etc. tp Thunder Hammer."
"**One** weapon can be chosen from the following list: Combi-weapons"
Thus, I may swap the boltpistol for two weapons from the first list and the boltgun for one from the second. 
I call it debatable because: take a captain in comparison and there it is perfectly clear what can be swapped for what. MC boltgun for **one** item from Pistols, Combi-weapons or melee and chainsword for **one** item from Melee or a storm shield. 

Again, I want to start a debate for the bs files because there **is** a point for handleing it with up to three weapons, even if it doesn't seem to be intended - after all I could take the given layout, swap the guns with the same guns **plus** a chainsword (or whatever). I don't play it this way but ruleswise I couldn't deny it anybody else to do it. GW didn't mention it in the FAQ either and a request of me so far yielded no response.

**Comment by acebaur** [comment]
You can exchange your two weapons for two items from the list, only one of which may be from the second list.

**Comment by Thairne** [comment]
"swap the boltpistol for two weapons from the first list"
I disagree.
If you go 1:2, you go against the general rule of "swap", which is one against the other.
This smells like TFG behavior since there is no precedent in any rules I am aware of that allows you to double the item count by trading 1 for 2 (with the exception of Lightning Claws maybe).
I strongly suggest not trying to enforce that and if someone tries to give him this look:
ಠ_ಠ

**Comment by GenWilhelm** [comment]
> Thus, I may swap the boltpistol for two weapons from the first list and the boltgun for one from the second.

That's not at all how it works. The wording is that you lose both weapons in order to pick items from the wargear list.

I do however agree with the conclusion that you are able to take a total of three items, two from the first part and one from the second.
The only issue is that it's not at all clear what the scope on the first restraint is. The wording on the second restraint implies that it only extends to the end of the melee/pistol section, and not across the entire list.

**Comment by ilaunchbury** [comment]
Now that GW have FAQed the Chaos champion list, they are in the same boat. I'm of the opinion that you only should end up with 2 weapons once you've swapped your default 2.

**Comment by flakpanda** [comment]
Im not changing it. If you want to be a TFG, go ahead. There will just be validation errors in your list.

**Comment by Hellgore1974** [comment]
Easy man... interesting that a debate about a wonky rule (that may be written like this on purpose!) is almost instantly turned into a "TFG" ad hominem attack. GenWilhelm caught the point. Of course you should only be able to swap 2 vs. 2 - especially as it is downright dumb that you can drop the basic guns, take them back AND get a third item if this was intended.

**Comment by flakpanda** [comment]
Please don't assume I am aggressive with my responses, just very matter-of-fact. This how it appears the list works:
<img width="171" alt="screen shot 2017-08-22 at 4 10 42 pm" src="https://user-images.githubusercontent.com/19719565/29587797-abe9a1c2-8754-11e7-83eb-13ce7adca7a5.png">
