### ISSUE TITLE
T'au Empire - Pathfinder costs off?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1384]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.04

**Platform:** Windows

**Dropbox:** No

**Description:** The problem is at the Pathfinder Team, when you add this unit the markerlights points doesn't count in the roster, that amount of points is doen's added. Another problem is when you're trying to add an Ion rifle or an Rail rifle, at the time you do this the unit is still adding markerlights. When you add one of this guns the points of the miniature doesn't count again for the roster.
Example:
This is the right way to do it:
              Pathfinder Team---->x5 Pathfinders---->5\*8pts=40pts----->2pathfinders with markerlights, pulse carabines&photon grenades---->2\*3pts=6----->3parthfinders with rail rifles---->3\*22pts=66pts----->TOTAL=112pts
How Battlescribe does it:
             Pathfinder Team---->x5 Pathfinder---->Markerlights, pulse carbines&photon grenades---->5\*3pts=15pts---->x3 Pathfinders with Rail rifles---->81pts(3x22pts)???!!!---->TOTAL POINTS---->121pts

---
Edited to fix formatting.

**Comment by GenWilhelm** [comment]
Not sure I see the issue here.

Pathfinders: 5pts per model.
Markerlights: 3pts each.
Rail Rifle: 22pts each.
Everything else: free.

Official way to do it:
5x Pathfinder: 5x5 = 25pts.
2x Markerlight: 2x3 = 6pts.
3x Rail Rifle: 3x22 = 66pts.
Total: 25+6+66 = 97pts.

BattleScribe way to do it:
2x (Pathfinder + Markerlight): 2x5 + 2x3 = 10+6 = 16pts
3x (Pathfinder + Rail Rife): 3x5 + 3x22 = 15+66 = 81pts
Total: 16+81 = 97pts

**Comment by amis92** [comment]
The OP seems not to understand that an entry in roster titled "Pathfinder w/ Rail Rifle" is for a model and a weapon/wargear. Maybe he used Chaos files before and the change is not yet clear for him.

Anyway, as @GenWilhelm above proved, points are correct. Closing.
