### ISSUE TITLE
Embedded HWS Models Overcosted: All AM Regiments

### ISSUE THREAD

**Issue by quindraco** [BSData/wh40k#1434]
**File/Catalogue:** Imperium - FW Elysians.catz, Imperium - FW Death Korps of Krieg.catz, Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.04.92

**Platform:** Windows

**Dropbox:** No

**Description:** In all three Regiments, an HWS model taken in a unit where the majority of the models have 1 wound is inexplicably overcosted relative to taking a unit consisting solely of such models, in violation of the rules covered in the relevant book's (Index: Imperium 2 or Index: Forces of the Astra Militarum) costs page in the relevant points appendix.  I am not fixing these costs myself, both because I am not confident I know how to do so correctly, and because this is a potentially contentious issue that ought to be recorded on the assumptions page here https://github.com/BSData/wh40k/issues/2 , and I am not willing to make these assumptions on behalf of the project.

This covers all 3 regiments the same way, so I will only provide documentation here for the Index: Imperium 2 rules on general regiments, but the exact same logic applies to both Elysia and Krieg, and I can provide documentation for those if needed.

Page 142 specifies these costs per model:
Infantry Squad 4
Heavy Weapons Squad 4
Veterans 6

When I open up Battlescribe, I can add Heavy Weapons Squads at 4 points per model, but if I add an Infantry Squad, the Heavy Weapon Model (which is identical in every respect to a member of a Heavy Weapons Squad) costs 8 points, not 4.  The same problem arises with a Veterans squad, where the model costs 12; it has no separate unit to consult, unlike with the basic infantry option, but presumably (this is where the assuming comes in) it should cost 6, as that is the cost per model for a Veterans squad.  It makes about as much sense to charge more for a Veterans Heavy Weapon model as it does to charge more for a Sergeant, and neither move is supported by the rules.

Elysia has this problem with Veterans Squads, and Krieg has it with Grenadiers and Engineers.

Note that Krieg has an ancillary problem: For no reason at all, Grenadiers and Engineers make opposite assumptions about whether or not the Heavy Weapons model is carrying the unit's special gun, a hot-shot lasgun or Krieg combat shotgun, respectively, both of which cost a point, affecting the cost of the model (and hence the entire unit).  It is this submitter's firm opinion that neither model is carrying said weapon; here is the relevant wording:

"Two other Engineers may form a Death Korps Engineer Weapons Team with a heavy flamer or mole launcher."
"Two other Grenadiers may form a Death Korps Grenadier Weapons Team with a heavy flamer.’"

In neither case does the unit's general wargear entry (below the statline, above the weapon rules) specify any additional wargear for these models, which, in general, means the models don't have any additional wargear - the Engineer Team has a heavy flamer or mole launcher and nothing else, and the Grenadier Team has a heavy flamer and nothing else.  If Battlescribe wants to assume differently, whatever it decides, it should make the same assumption for both models.

**Comment by quindraco** [comment]
As an addendum:  Grenadiers and Engineers Weapons teams *cannot* be carrying 1 hot-shot lasgun or 1 shotgun, respectively, because their rule adds the relevant Special/Heavy weapon, without replacing anything.  You can assume the model has 0 hot-shots or shotguns (if the wargear the models that formed it disappeared with them) or 2 hot-shots or shotguns (if it did not), but as neither model has any allowance for *replacing* any weapons with another, there is simply no basis for arguing that it is carrying 1 of the relevant weapon.

**Comment by amis92** [comment]
Heavy Weapons Team is an upgrade of the form "take 2 models and make them HW Team" in each entry except HW Squad. Thus BattleScribe counts HWTeam upgrade as "includes 2 model costs" - so in Infantry Squad it consists of 2 Guardsmen (2x4pts) and in Veterans - 2x6pts=12. Because HWSquad has explicit cost of 4pts/HWTeam "model" (which is 2 models), so is it in BattleScribe (so these guardsmen are actually 2pts/Guardsmen).

Do you need further clarification?

PS If you look closely in Infantry Squad with HWTeam selected, until you decrease Guardsman to 7x, you have an error - because it's 1xsarge, 2x for HWTeam and 7x normal.

**Comment by ilaunchbury** [comment]
re the Combat Engineers vs. Grenadiers weapon options.

1. Your statement that they have different behaviour, although correct, appears to be due to a missing constraint, rather than a deliberate decision. The engineers have a problem with their constraints which means they are not getting their default equipment (shotgun, frag & krak, acid gas bomb). In fact, you can give any model any number of acid gas bombs or shotguns if you want. The Weapon Team **should** have a single shotgun and its grenades and bomb by default, but doesn't due to this issue.

2. Heavy Weapons Teams in a Heavy Weapon Squad (for all armies) have one lasgun and their heavy weapon. The assumption has been made that Weapon Teams in normal squads should function the same way.

**Comment by quindraco** [comment]
> amis92: There is no basis in the rules for having an HW Team cost the same as 2 models, which I covered in my post.  The Index is actually very, very clear that the HW Team costs the same as 1 model, because it IS 1 model.  It is 1 model that replaces 2 models at once.  The Index clearly mandates that e.g. an Infantry squad costs 4 points per model.  An HW Team is a single model in an Infantry squad, so it should cost 4 points, just like a Sergeant does (or a single model in an HW Squad).

> Ilaunchbury:  The single biggest problem with your reasoning is that the Grenadier team should carry a hot-shot lasgun, by your logic; it does not, in Battlescribe, and there is no option to give it one.  As I said, the Grenadier and Engineer teams have identical rules wordings, so there is really no excuse for them working differently from each other.

**Comment by alphalas** [comment]
Hey @quindraco, I'm the primary maintainer on all the guard cats.

You're right; partially- there is an inconsistency with how I implemented HWTs inside squads. However, I disagree with your initial point.

You are citing the points for the Heavy Weapon * Squad*, which is the squad entirely composed of Heavy Weapon Teams; which are 4ppm; because you can *only* have 3 bases of HWTs in that squad. However, all other HWTs aren't just 1 model, they are 2 that count as 1, plus a heavy weapon. You have to pay for 2 first; there is no discount because the HWS HWTs are costed the same as a regular guardsman.

But you were right, it is inconsistently implemented. So, how I will resolve this is to add a second lasgun/hot shot lasgun to each base, since as you pointed out, the 2 guardsmen don't loose their default wargear when they create the HWT.
