### ISSUE TITLE
Aeldari - Ynnari: Hemlock wraithfighter cost issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1536]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.01.05

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** The point cost for the hemlock wraithfighter should be 211 and not 221. 

While it has spirit stones, these are not a vehicle upgrade as for the wave serpent, nor they come listed as equipment anywhere. In this case they are under special rules, and the 10 extra points should not be added to the cost. 

Listnon any major tournaments have these listed as 211, not 221. 

Thanks q lot for your great work

**Comment by kaintxu** [comment]
Hi,

I know this topic has been raised before and discarded, but just wanted to confirm this is right.

If you look at the wave serpent entrance this is listed  as wargear options. If you look into the points sections, the points for each unit says Points Per Model (does not include **wargear**)

If you go to the hemlock, this is under the abilities section, which is something you don't pay for. If he had to pay for them as a mandatory item instead of optative as for the wave serpents, they would show up in the description where it says it is equiped with 2 heavy d-scythes. An example is the wraithblades. Even though the forcefield is describes in the abilities section, it specifically appears as a wargear options, so they have to pay for it.

Even if the spirit stones show up as being 10 points, they show in the wargear section of the points index under other wargear, so you only pay for them as such.

To put an example,

**Comment by Alvirulan** [comment]
I don't know if this can help : 
https://www.facebook.com/permalink.php?story_fbid=1851315258522438&id=1575682476085719

**Comment by Kohato** [comment]
All wargear is listed as "Abilities" on the datasheets - IE: Resurrection Orb Necron models.

**Comment by FarseerVeraenthis** [comment]
This is boring.
It has a points cost in the index, so you have to pay for it.
