### ISSUE TITLE
Aeldari - Craftworlds - Codex Update

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#1678]
The Codex update is being prepared, it will be available probably early next week.
I'll do my best.

**Comment by Viper666-Qc** [comment]
Maybe this have been answered already but I have a question about missing weapons options in the codex vs the index (ex: for exarchs). Will they have separate entries in the BS roster?  

"""
https://www.warhammer-community.com/2017/07/05/codexes-your-questions-answered-july-5gw-homepage-post-2/
There are a few options that are missing in the codex that appear in the index: why is that? Does that mean I can’t use these models in my army anymore? 
codexes are designed to give you rules for the current Warhammer 40,000 range. There are a few options in the indexes for some Characters and vehicles that are no longer represented in the Citadel range – certain Dreadnought weapons that don’t come in the box, or some characters on bikes, for example.
Don’t worry though, you can still use all of these in your games if you have these older models. In these instances, use the datasheet from the index, and the most recent points published for that model and its weapons (currently, also in the index). 
"""""

**Comment by FarseerVeraenthis** [comment]
At present, yes, but I need to review side-by-side to see exactly how many units it has an impact on and figure out the best way to represent the situation in BS.... hence why it's not released already :smile:

**Comment by alphalas** [comment]
Also, @viper666-qc, that’s more a question for the gitter anyway ;)

**Comment by xkyneticx** [comment]
Please add Bonesinger rules to craftworlds https://www.warhammer-community.com/2017/10/24/free-rules-for-the-craftworlds-bonesingergw-homepage-post-2/

**Comment by ilaunchbury** [comment]
- I personally don't like the "Abilities as wargear" layout, but that is personal preference. I think it makes things cluttered in the roster editor.
![image](https://user-images.githubusercontent.com/29306451/32266696-45191806-bee0-11e7-9178-ba8f08744785.png)
IMO, only the Pistol, Psychic powers and Witchblade/Spear need to be in that list. All the rest should just be Profiles rather than Selection Entries.
- Battle Focus doesn't have the first set of parentheses.
- Smite has the "If manifested," caveat in its description. All the other powers should have it too.
- Warlock Conclave Psyker table looks messy, consider using modifiers to change the values based on the number of models?
- Warlock Conclave, I'd consider making "Destructor" an ability rather than a power as you've lost the details of how Smite works.
- Codex Autarch should be 4PL.
- Sunburst grenades on WJG Autarch should be min1, max 1.
- Melta bomb has HTML tags in it's description (that's probably a GST issue).
- Jain Zar's Cry of War Unending has "units that have **chared**" in the second sentence.
- The Maugetar's "rending" rule could probably be moved into the two profiles, rather than having a separate line.

**Comment by ctdavids** [comment]
The Autarch Skyrunner shouldn't have the forceshield.  It now has the "Peerless Agility" rule (changed from index) so no more randomly spending 6 points.

**Comment by FarseerVeraenthis** [comment]
Right then boys and girls, give it a whirl and lemme know what needs fixing...

**Comment by FarseerVeraenthis** [comment]
Please report bugs in #1704
