### ISSUE TITLE
Warhammer 40k is missing from repository list

### ISSUE THREAD

**Issue by oarmisaelo** [BSData/wh40k#1703]
**File/Catalogue:** 
Warhammer 40k data file
**BattleScribe version:** 2.01.
2.01
**Platform:** Windows/iOS/Android/Mac/Linux
iOS
**Dropbox:** Yes/No
No
**Description:** Detailed issue description.
It has lost from repository list

**Comment by jacknimble23** [comment]
Having the same issue! I've tried reinstalling, and updat By, and it's not there. I don't even see it in the repository list on the website.

**Comment by DerSeb86** [comment]
Same issue here, as the guys above.

**Comment by alphalas** [comment]
Check the appspot link (where BS downloads from). If you don’t see it on the list there, that is the issue - unfortunately after a release the 40k link “falls off” appspot; we don’t know why, and there’s nothing we can do to fix it. It will eventually come back, usually within 8 hour or so, and you will be able to redownload as normal.

**Comment by DerSeb86** [comment]
Thanks, for quick answer. No it is not in the list.  Okay each others System. Okay i'll try later again.
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 03.11.17, 06:58, Jon Kissinger <notifications@github.com> schrieb:
Check the appspot link (where BS downloads from). If you don’t see it on the list there, that is the issue - unfortunately after a release the 40k link “falls off” appspot; we don’t know why, and there’s nothing we can do to fix it. It will eventually come back, usually within 8 hour or so, and you will be able to redownload as normal.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BSData/wh40k","title":"BSData/wh40k","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BSData/wh40k"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alphalas in #1703: Check the appspot link (where BS downloads from). If you don’t see it on the list there, that is the issue - unfortunately after a release the 40k link “falls off” appspot; we don’t know why, and there’s nothing we can do to fix it. It will eventually come back, usually within 8 hour or so, and you will be able to redownload as normal. "}],"action":{"name":"View Issue","url":"https://github.com/BSData/wh40k/issues/1703#issuecomment-341627529"}}}
