### ISSUE TITLE
Aeldari - Craftworlds - Autarch power sword relics validation

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1736]
**File:** Aeldari - Craftworlds.catz

**BattleScribe version:** 2.01.06

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Autarch with Swooping Hawk Wings: Error with Power Sword and Shard of Anaris/Firesabre. When Remnent equipped error says too many Power Swords (max 0) but when Power Sword no select error reads Minimum 1 Power Sword needed. Maybe have Sword choice category: Power Sword/Shard/Firesabre?

**Comment by FarseerVeraenthis** [comment]
ahhh.... I might have missed a modifier somewhere, I'll see what I can do :smile:

**Comment by alphalas** [comment]
Actually, arguably it is correct with how relics work now. You *NEED* a PS to take a Shard of Inaris; and if the "replace with" text is there, it's perfectly fine.

**Comment by FarseerVeraenthis** [comment]
the validation is still not correct because I missed the points.
This stands for all relics as well.
Either I need to allow both, or allow only one choice but with the correct points cost - so there is work to be done either way for the Power Swords and that means I need to check the other relics as well...
