### ISSUE TITLE
Shouldn't this be merged with SM? 

### ISSUE THREAD

**Issue by asorel1942** [BSData/wh40k#1817]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** No

**Description:** As it stands, units from this list can't be in the same detachment as regular Space Marine units. This isn't really reflective of the game rules, and makes list building a bit cumbersome.

**Comment by alphalas** [comment]
If you’re talking about FW Astartes; trust us you don’t actually want them merged just because of file size. If you follow the guide for child detachments, and have FW astartes as the parent the relic constraints work too. When @jonshickov gets around to it, we have requested improvements to how child/parent detachments display in the output.
