### ISSUE TITLE
Imperium - Blood Angels: Inceptor cost incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#1960]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.08

**Platform:** Android

**Dropbox:** No

**Description:** When using the Imperium - Blood Angel V25, the inceptors plasma incinerators cost is not the good one, it should be 34 points per model instead of 86

**Comment by Crowbar90** [comment]
I'm not sure what you're referring to, since Inceptore don't have access to plasma incinerators. However I've rechecked all Primaris weapons and I noticed there was a mistake in the points calculation for Inceptors' plasma exterminators. Now they cost 59 points per model (25ppm base + 2*17ppm plasma exterminators). Please comment here to let me know if this was the bug you were reporting or if there's something I overlooked.
