### ISSUE TITLE
"Leman Russ Battle Tanks" turret weapon selection UX

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#1989]
**File/Catalogue:**  	Imperium - Astra Militarum.cat

**BattleScribe version:** 2.01

**Platform:** Windows/iOS/Android/Mac/Linux

**Description:** The unit "Leman Russ Battle Tanks" has an unnecessarily complex method for selecting a turret weapon. It should have a single "Add Leman Russ Battle Tank" and then be similar to the tank commander's entry, selecting the turret from a radio menu, with the Battle Cannon as the default radio selection.

Since this was locked without even being looked at, "it's not difficult" is not an excuse for sloppy design. It makes changing your mind difficult and quick reselecting hard. If you want to change your turret, it resets ALL other options, that is not good design.

**Comment by alphalas** [comment]
It’s hardly difficult- you pick the variant and go to town.

**Comment by alphalas** [comment]
@baconcatbug, no I'm intimately familiar with what you're referring to. HOWEVER; your complaint is of a minor inconvenience, not an actual problem. Still not changing it.

**Comment by alphalas** [comment]
Also, might I add that that kind of change, just for the lulz, will probably break EVERY. SINGLE. PREMADE. LIST. Guard players have; seeing as the russ is literally the most popular unit in the codex.

**Comment by BaconCatBug** [comment]
So, because of your sloppy work, you can't even fix it? I've had my lists
break before too, what's your point?

**Comment by FarseerVeraenthis** [comment]
I'm sorry @baconcatbug but you're wrong. The way the file is currently implemented results in the least number of clicks to build a squad of default tanks. Implementation of your suggestions would result in more clicks and is therefore inefficient.
Also, since the different turrets actually build tanks with different names, just selecting the turret would be incorrect.
I know Internet 101 says do not feed the troll, but you are categorically wrong in your comments of "sloppy design" when the current implementation is actually the most efficient way of doing it...!

**Comment by BaconCatBug** [comment]
Selecting a different turret does NOT build tanks with different names. No
matter the turret the model name is still Leman Russ Battle Tank.

**Comment by WindstormSCR** [comment]
Have you tried not being a complete ass when making requests? The amount of work involved in any major change to a unit is non-trivial, which you could experience yourself if you made a fork and tried to change it yourself just to see why it's implemented the way it is.

Try to remember that everyone working on this are volunteers, doing it because we want to, not for any kind of thank you from the community, and for no money at all.

**Comment by BaconCatBug** [comment]
I never said it was trivial, I said it was sloppy and a detriment to the
end user.

**Comment by cartag** [comment]
Don't mind @BaconCatBug, he's a tool. Remember several months ago, the guy who cried because I was rude to him? Yeah, same asshole.

**Comment by BaconCatBug** [comment]
So wait, you were rude but I am the one at fault? That makes no sense.

**Comment by cartag** [comment]
I edited one post after you chastised another user for having the audacity to use PL instead of points. You in turn claimed to report us to GW because you got your feelings hurt. Get the fuck out of here.

**Comment by FarseerVeraenthis** [comment]
I'd love to know your logic process that leads to the statement that efficiency is sloppy... What's sloppy about it?

**Comment by BaconCatBug** [comment]
The fact the turret weapons are split into individual units is not
intuitive and prevents changing on the fly. If I set up a Leman Russ with
various upgrades, then want to swap the turret, I have to delete and
rebuild from scratch.

Furthermore, from a rules standpoint, you're changing the name of the unit
on the roster to something that doesn't exist as a datasheet. The name of
the unit is always "Leman Russ Battle Tank" regardless of the turret weapon.

Further Furthermore, the Tank Commander already has the turret option as a
radio option, so there should be no reason for the Leman Russ Battle Tank
unit to have their turrets selected a different way.

**Comment by amis92** [comment]
I'm reopening the issue requesting @alphalas to re-evaluate the request possibly taking deferral to next major update as a resolution but leaving him full scope of final decision.

The arguments of both sides are valid and as much as we seek to mirror book selection mechanisms, breaking (possibly) every single AM roster might be a little too much on its own.

---
I feel the discussion has been unnecessarily heated and at times offensive, derailing into semi-personal quotes and laundering of the past. That is not how our communication is expected to be done. **Please proceed with neutrality at your best.**

**Comment by FarseerVeraenthis** [comment]
To continue the discussion then, I feel that the turret weapon defines the role of the tank in the army and the rest of the options fine tune this main role.
As such, I feel like you should choose the role for the tank (turret) then add options, as the entry is currently built.

**Comment by BaconCatBug** [comment]
I feel that you should follow the actual rules as laid out in the codex,
where the turret is nothing more than another option, no different to the
sponson options.

**Comment by FarseerVeraenthis** [comment]
A coupe of points and a little question;

Do you @BaconCatBug exclusively use desktop? or exclusively use mobile? or a bit of both??

Some of the data authors have taken time to speak to some players (and are in fact players themselves), and the players said that, as currently implemented, they find it easier to keep track of which model has which options when checking lists on mobile, and with printed lists when using minimal output.

To your comments in your post;
- "as laid out in the codex" <-- The first option on the list in the codex is the option to replace a battle cannon with one of the other turret options. The current implementation incorporates this replacement directly because you choose your turret as the first option.
- "the turret is ... no different to the sponson options" <-- unfortunately there is a difference, for the turrets "Any model may REPLACE...", while for the sponsons "Any model may TAKE...". 
As such the current implementation DOES follow the rules as laid out in the Codex.

While your suggestion does offer the advantage of being able to change turret "quickly" without losing the options, that is the only advantage over the current implementation. 
The disadvantages in comparison with the current implementation are;
- more clicks/taps to select a turret (other than the battle cannon) initially, 
- less "obvious" display of which tank/turret is selected in the roster view on both desktop AND mobile,
- less "obvious" display of which tank/turret combination has which sponson options on both desktop AND mobile,
- making the change will break every list containing any Leman Russ options

So you can see that while you might not find the current implementation meets your expectation/requirements/demands, there are a number of solid reasons why it has been built this way and is unlikely to be changed. We have to consider a solution which suits ALL users and currently the implementation does that.
Note that there is nothing stopping you from creating a copy of the datafile on your own computer and modifying it to meet you requirements. As you noted, the Tank Commander already uses a radio button, so you can use that as a template for your modifications to the Leman Russ Battle Tanks entry.

Finally, I will leave this ticket open for any additional comments and for final disposition from @alphalas to close it or incorporate it.

**Comment by BaconCatBug** [comment]
It's clear that the contributors here are insular and hostile to any form
of feedback, as I have found to be the case in most open source communities.

Your nitpick about replace vs take is not relevant. Once again I regret
ever bothering to try and make suggestions.

**Comment by BaconCatBug** [comment]
Just lock it like you initially did, you're all a bunch of liars and
feedback-phobic.

**Comment by FarseerVeraenthis** [comment]
Unfortunately @BaconCatBug you are representative of the scum of the internet.

Amis re-opened the issue to allow for further discussion from a non-personal point of view, because we're not "hostile of feedback", I have been trying to DISCUSS the issue, giving positives/negatives to the two different implementations because, as Amis said, both sides are valid. I gave you a reasonable justified argument for leaving the implementation as it is, and you reply with nothing but vitriol. This actually makes it appear that YOU are the one who cannot accept feedback, and certainly cannot accept the fact that we do not hold the same point of view as you do.

As for my "nitpicking" about Replace/Take, we have to be very careful to follow the RAW. Replace/Take is NOT a nitpick because GW have previously stated that the order of options in the datasheets is important. In this regard the current implementation matches the Codex explicitly while also providing a UX benefit for a significant proportion of our users.

Finally, and I cannot state this strongly enough, calling people liars without any justification is a direct personal attack and simply will not be tolerated here.
