### ISSUE TITLE
Imperium - Blood Angels - Captain Weapon Point Discrepancy

### ISSUE THREAD

**Issue by egruber** [BSData/wh40k#2021]
**File/Catalogue:**  Imperium - Blood Angels

**BattleScribe version:** 2.01.09

**Platform:** iOS

**Dropbox:** NA

**Description of Issue:**
The weapon loadout for a Captain with dual lightning claws registers as 14 points as opposed to 12 points. 

**Steps to Reproduce:**
1. Create new roster with Imperium - Blood Angels
2. Select any force organization
3. Confirm Roster Creation
4. Select “+” on HQ
5. Select Captain - 77pts
6. Unselect Master-crafted Bolt gun
7. Select Lightning Claw under “1x Melee Weapon”
8. Select Lightning Claw under “1x Melee/Ranged Weapon”

**Expected Results:**
Upon selecting the second Lightning Claw, the price of the Lightning Claw under “1x Melee/Ranged Weapon” should adjust to 4 points. 

**Actual Results:** 
Lightning Claw under “1x Melee/Ranged Weapon” adjusts to 6 points.

**Misc:** 
This issue does not recreate on Imperium - Space Marines. This issue also does not reproduce if you select dual Lightning claws for a Vanguard Veteran. Currently appears to be isolated to the Captain

**Comment by Crowbar90** [comment]
I'm currently in the process of updating the catalogue according to the Codex. I'm going to check this out as soon as I've finished the Codex update.

**Comment by egruber** [comment]
Thanks for the great response time to this issue! You are doing great work.

**Comment by Crowbar90** [comment]
Ok, I checked it. You should just select both Lightning Claws as you're currently doing: this way one will cost 8 pts and the other one 6 pts. Now select the first one again and it will adjust to 6 pts, making 12 pts total. I'm not changing it to 4 pts because if I did that and then selected the first one again it would adjust to 4 pts too, leading to dual claws for 8 pts. The only way to fix this behaviour would be by adding a "Lightning Claws (pair)" option, but it would be a significant change. I'm going to do it eventually, but there is some more pressing stuff I have to work on currently. Anyway thank you for your detailed bug report!
