### ISSUE TITLE
Death Korps of Krieg missing Warlord Traits and Relics (No, the FAQ does not forbid them)

### ISSUE THREAD

**Issue by GenericCola** [BSData/wh40k#2033]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows 10

**Dropbox:** No

**Description:** 
Contrary to what the person who closed this topic last time said, the FAQ does not say anything about Krieg access to generic Astra Militarum warlord traits and relics; it EXPLICITLY states that Krieg cannot use REGIMENT SPECIFIC warlord traits, doctrines, etc. That has no effect on any of the warlord traits and relics that are not regiment-specific, though.

Currently in Battlescribe, Death Korps of Krieg only has access to the generic warlord traits from the core rulebook. As per the wording of Codex: Astra Militarum AND the FAQ, Krieg Warlords should qualify for generic Imperial Guard Warlord traits and relics as well, as long as they are not regiment specific-- they are 1) A character with the Astra Militarum keyword, and 2) in a regiment comprised entirely of Astra Militarum units. They meet the criteria for them, and nothing says that they cannot use the Warlord traits from the Codex. I see no reason that they should not be able to.

That FAQ specifies that they cannot use any REGIMENT SPECIFIC rules. The generic Astra Militarum warlord traits are not regiment-specific.

The question in the FAQ was asked because originally (as per the wording of Doctrines) , Krieg were able to take a Regimantal Doctrine of another regiment, as they were "a regiment without a Doctrine in this book," and the Codex allowed them to use a Doctrine since they didn't have their own. As per the FAQ,, they are no longer allowed to use a doctrine, but there is NO REASON that they would be unallowed to take the REGULAR Astra Militarum warlord traits, relics, and strategems, as per the specific rules/FAQ released by Games Workshop. This FAQ does not say anything about non-regiment specific items/traits, and citing it is not a valid reason to close this report.

**Comment by alphalas** [comment]
@GenericCola; please refrain from combative bugreps; we are all volunteers here and are only human. There was no need for the second bugrep, as I took it to the other data devs to discuss. I’m not at all discounting your bugrep because you presented a case arguing I was wrong , reasonably.

Making aggressive/combative bugreps after the same initial bugrep is counter-productive and just makes us *less* likely to be willing to discuss with you as reasonable adults. I am closing this bugrep and reopening the initial report; if you wish to discuss further with us, please do so on gitter.

**Comment by GenericCola** [comment]
I wasn't sure how bugreps worked, I was under the impression that once it was closed/removed from the frontpage, nobody would see/heed the argument I presented.

Noted.
