### ISSUE TITLE
Dark Angel Tac Sarge

### ISSUE THREAD

**Issue by thefbgnome** [BSData/wh40k#2086]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
the tactical sarge should be allowed 2 weapons options... currently can only have one.

**Comment by ilaunchbury** [comment]
Please elaborate. This appears to be working fine in DA v33.

**Comment by thefbgnome** [comment]
I am using DA v 38... a tac sarge should be able to have a plasma pistol
and a power sword... when I try this I get the following errors (see
attached) this is the same in Android and iPad version...

**Comment by thefbgnome** [comment]
Why is this closed? It is still an issue... Tac Sarge can have two items
the current file only allows you to take one... the codex says "The Space
Marine Sergeant may replace his bolt pistol AND boktgun with items (plural)
from the Sergeant Equiment list" (emphasis mine)

**Comment by alphalas** [comment]
They were closed by a comment, which means when the next release goes out they will be fixed. They are fixed on the master.

- Jon[K]

**Comment by thefbgnome** [comment]
Nvm... I see you fixed in v 39/40... havent got it yet through the push ...
thanx

**Comment by alphalas** [comment]
![87568974-aa6c-436a-b5c9-cb8db3d156ac](https://user-images.githubusercontent.com/15703066/34367360-cd9e4a4e-ea77-11e7-9337-d2f3665d5d4c.jpeg)
@thefbgnome  when you see something that looks like that that says closed by, that means there is a commit that was pushed to the master that closes whatever the issue is and fixes it. The push to your device will not happen until after the next release goes out to appspot which includes said commit.

**Comment by thefbgnome** [comment]
Yeah I figured that out two minutes after I asked the question LOL... thanx
