### ISSUE TITLE
Imperium - Deathwatch: HW Veteran should be able to take a storm shield

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2296]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Veteran w/ heavy weapon is missing the option to take a storm shield. The shield isn't a weapon, so it doesn't get replaced when the veteran swaps all their weapons for grenades and a heavy weapon (per the FAQ).

**Comment by ilaunchbury** [comment]
I don't believe this is correct. The storm shield is not a separate option, it is included in the _Deathwatch Equipment_ list.

If a Veteran replaces "all their weapons with frag grenades, krak grenades and an item from the _Deathwatch Heavy Weapons_ list" as per the FAQ, they no longer have a boltgun to replace with "two items from the _Deatchwatch Equipment_ list, so they have no way to get a storm shield.

You also can't replace the boltgun with a storm shield and X and then swap those weapons for the heavy weapon option, because wargear replacements only happen once.

**Comment by acebaur** [comment]
There is no order of operations in 40K. You can only do one thing that requires you swapping your weapons on the bullet point list per model. If you could do otherwise then it would say so. Furthermore the SS is considered a weapon for all intents as it is included in the list of weapon options. Otherwise it would be listed like the combat shield on a separate line.
