### ISSUE TITLE
Chaos - Chaos Space Marines: Daemons in CSM catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2357]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** Chaos marines, legions and daemons.
When building detachments, battlescribe currently allows the daemon included in the codex to be added to detachments as normal. This is perfectly legal, but will limit that detachment from benefiting from some codex abilities. 
When applying filters for different legions, the daemon selections are filtered based on god allegiance.  This is not correct, as all of the daemon units in the codex do not have a legion, cannot benefit from legion traits and will prevent others in the same detachment from benefiting.
The current layout has caused some confusion, and I've seen lots of examples of people assuming they can slot daemon units into thier lists with no problems, when in fact there are huge disadvantages.  
I'm not sure what the best response to this problem would be. For list building purposes I would prefer daemons outside of the daemon codex didn't appear as options (or were an optional filter) in legion detachments. I would also like to see a slot for setting aside summoning reinforcement points/ units. 

Sorry for being longwinded, thanks for reading.

**Comment by MountyChris** [comment]
Didn't think that would flag me as anon. Ah well.

**Comment by alphalas** [comment]
Yeah apparently if you submit a bug rep through BattleScribe, it’s always anon.

**Comment by skonk** [comment]
With regards to the last point about calculating points for summoning. I tend to just add an "Unbound Army" detachment and drop the units in there so I can set their wargear and calculate the points.

**Comment by Mad-Spy** [comment]
This is an interesting point. As you say, BS is not allowing people to do anything that is not legal in the rules.

BS is not intended to replace owning a Codex. If people don't have access to the full rules and misunderstand how to build a valid "Chaos Space Marines" detachment, that is not our fault and I don't think it is our responsibility to fix.

Daemons are currently filtered by legion because some legions must have a specific keyword (i.e. World Eaters must be Khorne) and so can't summon daemons which don't have that keyword.

In terms of summoning, I think @skonk's suggestion is probably the right way to go. Technically, choosing the summoned unit doesn't happen until after the dice are rolled, but obviously, people need to know how many points to reserve based on what they expect to summon. If you're summoning something that isn't in the CSM Codex, you basically need to add a Daemons detachment anyway so this covers it.

Having said all that, I think that your suggestion of removing the Daemons from the CSM catalogue may be the right way to go. I'll get some more input and then see where we got to.

**Comment by OftKilted** [comment]
The issue appears to be not that they can be taken, but that people are trying to take them, and Legion rules and (because they don’t have the HERETIC ASTARTES keyword) they should likely be loosing out on the Strategems as well.

Blocking Legion rules would be more in line with a legitimate solution, rather than attempt to enforce a specific type of list making (ie no Daemons in CSM lists)
