### ISSUE TITLE
[7th Edition] Dark Angels: Formations are unselectable

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2442]
**File:** Imperium - Dark Angels.catz

**BattleScribe version:** 2.01.14

**Platform:** Android

**Dropbox:** No

**Description:** In the 7th edition files, there is a bug that prevents me from creating, editing, or even viewing any dark angels formation. I have attempted to submit a bug report on the 7th edition bug reporting system but that is, for some reason, not working also. Please at least assist me in reporting this bug to the right person.

**Comment by GenWilhelm** [comment]
The reason you can't submit a report for 7th edition data is because the repository has been archived, as it hasn't been actively maintained for at least 9 months.

I can take a quick look, but there's no guarantee that it'll ever be fixed.

**Comment by GenWilhelm** [comment]
As far as I can tell, there's a few formations with rogue categories that don't exist any more (they were probably deprecated with later versions of BattleScribe), so it can't resolve the link, and therefore fails to load the force.

Here's a fixed version of the file; you just need to unzip it and then import it into BattleScribe (Manage Data > Import data from file).
[Dark Angels - Codex (2015).zip](https://github.com/BSData/wh40k/files/1710770/Dark.Angels.-.Codex.2015.zip)

It probably wont be rolled out through the official channel, since we no longer support the data set, but I hope this helps regardless.
