### ISSUE TITLE
Imperium - Space Marines: Captain wargear issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2510]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** No

**Description:** Captain has a bolt pistol by default.
It should instead have a master-crafted boltgun.
Option to swap master-crafted boltgun for a pistol, combi-weapon, or melee weapon.
Option to swap chainsword for storm shield, relic blade, or melee weapon.

**Comment by Mad-Spy** [comment]
All of these options are available in the current version of the Space Marine catalogue, as shown below. Is your option dialog hidden somehow?

![image](https://user-images.githubusercontent.com/29306451/36369895-dfe77538-1554-11e8-8086-5bc38dcaf5a7.png)

The Captain will always have at least 1 bolt pistol because he does not have the option to exchange it.
