### ISSUE TITLE
Chaos - Death Guard: Daemons missing

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2537]
**File:** Chaos - Death Guard.catz

**BattleScribe version:** 2.01.20

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** All of the nurgle demon list entries avalable in the DG codex are not available in the battle scibe DG list. No I shouldnt have to take another detachment from the Demon codex when the units I want are in the DG codex.

**Comment by Mikle103** [comment]
Please see #2445 for the reasons behind this.

Including Daemons in your Death Guard detachment will disqualify it from using any Death Guard specific special rules because the Daemons do not have the DEATH GUARD faction keyword.

If you still want to include Daemons in the same detachment, add a child detachment of Daemons.
