### ISSUE TITLE
Imperium - Grey Knights: Techmarine issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2552]
**File:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.09

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
- [x] Techmarine is a character and therefore should be able to equip a relic.
- [x] Techmarine power level

**Comment by Pukwudji** [comment]
Also Power Level should be 7 not 8, according to GK codex.  Space Marine Codex costs equipment differently, so although overall points are correct we don't pay +1PL for Servo-harness.  Effectively we pay for 2xServo-arms, Power Axe, Flamer and a Plasma Cutter, instead of Power Axe, Servo-arm and Servo-harness.
