### ISSUE TITLE
Chaos - Death Guard and Thousand Sons Daemon Prince

### ISSUE THREAD

**Issue by Andy377** [BSData/wh40k#2711]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/

**Dropbox:** No

**Description:**
Daemon Prince of Nurgle in Death Guard codex does not have the option for a warp bolter.  this option needs deleting from Battlescribe.
Daemon Prince of Tzeetch in Thousand Sons codex does not have the option for a warp bolter.  This option needs deleting from Battlescribe.

**Comment by skonk** [comment]
The "Daemon Prince of Nurgle" in the Death Guard data file has no Warp Bolter option as per the Codex; but that data file does include the Index version of the Daemon Prince (since it is still a usable unit) which does correctly include the Warp Bolter option.

The Daemon Prince of Tzeentch in the Thousand Sons data file is incorrectly listing the Warp Bolter as an option though.

**Comment by Andy377** [comment]
Thanks, my bad

On Mar 23, 2018 14:56, "James" <notifications@github.com> wrote:

The "Daemon Prince of Nurgle" in the Death Guard data file has no Warp
Bolter option as per the Codex; but that data file does include the Index
version of the Daemon Prince (since it is still a usable unit) which does
correctly include the Warp Bolter option.

The Daemon Prince of Tzeentch in the Thousand Sons data file is incorrectly
listing the Warp Bolter as an option though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BSData/wh40k/issues/2711#issuecomment-375691916>, or mute
the thread

**Comment by Mad-Spy** [comment]
It depends on your reading of the Designer's Commentary and how you interpret the changes from Index to Codex. We've had people argue it both ways, so I'm supporting both as per Rule 0 until GW clear it up.
