### ISSUE TITLE
Chaos - Chaos Space Marines: Weapon config interactions on Terminators

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#2841]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.10

**Platform:** Windows

**Dropbox:** No

**Description:** Chaos Terminators: When you add terminators to the unit and start to change their weapon configuration, it alters the configuration of other terminators, not just the selected target. E.g. If there are 7 terminators and I try to set 5 with combi plasma and 2 with combi bolters, it will randomly alter some of the combi plasma selections and their respective points values. This tends to occur once you increase the unit size above 5.

**Comment by Mad-Spy** [comment]
I'm not able to reproduce this. However, when you add a new Terminator, it will be added above any you have switched to Combi-plasma, because they are always sorted alphabetically, so the new ones (which have a combi-bolter) will appear in the middle of the list.

Perhaps this is what you are seeing?
