### ISSUE TITLE
Imperium - Grey Knights - Psyker Description Possible Inconsistencies

### ISSUE THREAD

**Issue by Pukwudji** [BSData/wh40k#2856]
**Grey Knights:** 

**BattleScribe version:** 2.01.10.102

**Platform:** Windows

**Dropbox:** Yes

**Description:** Grey Knight Librarian should be listed as having 2 denies not one.

Also inconsistencies in the way Psychic powers are detailed:  Draigo and Voldus have the description from the Codex (C), all others have a numerical chart (NC).  When a numerical chart is used 4 of the units include Smite under Powers Known, the rest do not.

I propose all units should have Psychic powers detailed in the same way, in my opinion this should be in the numerical chart and should include the wording for Smite.  But then I'm not the maintainer ;)

As an aid I've looked through the Codex and on Battlescribe and my findings are attached
[GK Psychics.txt](https://github.com/BSData/wh40k/files/1913256/GK.Psychics.txt)
:

**Comment by tekton** [comment]
What version of the GK cat are you looking at? There should be a number after a "v" in the name of the army you're choosing. That seems like you're looking at an older version as the powers changed a few times between v5 and v18.

**Comment by Pukwudji** [comment]
I'm using v18, I must admit I thought that there had already been an issue raised about the librarian being wrong, so I'd already deleted my data and re-downloaded it.

**Comment by tekton** [comment]
I know the librarian is wrong, was going to get back to it after the FAQ; thanks for the reminder.

The other parts I'm not sure I agree; they're somewhat "inconsistent" from your point to make them more consistent on the back end- so it's a feature! The ones that know smite have it attached, so I'm actually more inclined to finish out removing that smite is a known power due to it being on the unit when you look at the roster, thus showing that it's a known and available power.

I'm also not sure what you mean by numerical chart as I don't see one and took that out a long time ago. Maybe a screenshot would help on that?

**Comment by Pukwudji** [comment]
Hi Tekton, this is what I mean by a Numerical Chart: 
![image](https://user-images.githubusercontent.com/36790874/39431200-e481ecee-4c87-11e8-906a-2e768fdb7216.png)

Whilst this is the Codex format: 
![image](https://user-images.githubusercontent.com/36790874/39431234-ffe9a60c-4c87-11e8-92c7-a11911a1eb5f.png)

Hope this helps explain what I meant

**Comment by tekton** [comment]
That does explain what you meant better, thanks.
