### ISSUE TITLE
unnecessary clutter detachments vanguard low

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#2966]
**File/Catalogue:** 
Imperium - Sisters of Silence
Imperium - Officio Assassinorum
Imperium - Legion of the Damned
**BattleScribe version:** 2.01.12
**Platform:** Windows/iOS/Android/Mac/Linux
**Dropbox:**y 

**Description:** Detailed issue description.
unnecessary clutter wh40k drop down menu selection of detachments vanguard some one just updated beta battle rules before this date to negate adding in unnecessary attachments to the bat files and just offered to use hq or not that was better then having to select a new file source to navigate the menus to just select one thing,.

**Comment by amis92** [comment]
@williamcaw can you please edit the description? It's very, very hard to read without casing and punctuation. Otherwise we reserve the right to ignore such feedback as unreadable. Providing us with clear description of your problem is your responsibility. Guessing about what you mean is *definitely* not ours.

**Comment by williamcaw** [comment]
before to day there was an option to say i didn't need hq in No force org slot for these detachments . in the April 25 update some one added an extra slot in the  drop down section detachments it is now cluttered.
