### ISSUE TITLE
Ease of use: vanguard “no force org:no hq -1cp” moble the item is missing

### ISSUE THREAD

**Issue by williamcaw** [BSData/wh40k#2968]
**File/Catalogue:** 
"Imperium - Sisters of Silence"
"Imperium -  legion of the damned ""Imperium - Officio Assassinorum"
**BattleScribe version:** 2.01.12

**Platform:** /iOS/Android/

**Dropbox:** /No

**Description:** crash error vanguard detachment ease of use
 I’m gonna keep hounding you to do work instead of being lazy and adding anew slot in to detachments item in question was in v1.1.35 More from the FAQtory

**Comment by williamcaw** [comment]
Moble is cranky as hell adding a new slot for detachments is not the way to go.

**Comment by williamcaw** [comment]
There is no limitations to battle Scribe to add this in

**Comment by williamcaw** [comment]
Darvit mobile page

**Comment by amis92** [comment]
@williamcaw If there are no limitations, why don't you make a pull request with changes you ask for? Maybe we're dumb not to get it how you want it implemented; show us. It's open source, everybody can contribute.

Right now you're writing in thrash style, not really putting in effort into describing what you expect. It'll be probably much easier if you just provide the material proof of your idea/concept/demand.

**Comment by alphalas** [comment]
@williamcaw, the extra detachments were added to the selector specifically for their own cat files. The reason why is because the limitation of BS I mentioned; you cannot modify thing in the GST from a cat file. All standard detachments are located in the GST, meaning that the special snowflake detachments for SoS, OffAssassins, and LoD need to be in their own cats. If we had put them in GST, there's nothing that could stop a user from using a SoS detachment for Astartes, for example. By putting the individual snowflake detachments in their own cat file this is prevented; those special detachments only being selectable if the specific cats are used, and only for those cats.

I saw you mention something about a No Force Org slot selector that could remove the 1hq requirement; this unfortunately is also not possible. For something to count as a HQ, it needs to be in the HQ slot selection. In addition, even *IF* it were possible, putting something like that into the no force org slot section is also a bad idea from UX standpoint; it makes it harder to track just how many Cps an army really has; while the current implementation makes it easy to glance across the list and see for yourself the annotations in the detachment names.

So no, it's not we're being lazy or anything else. it's balancing UX with the limitations of BS.
