### ISSUE TITLE
T'au Empire: Strike and Breacher Team drone selection issue.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3039]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Dropbox:** No

**Description:** Bug: Tau Strike and Breacher team's allow you to take a single drone, when they are restricted to taking either 2 tactical drones or 1 tactical drone and 1 guardian drone.

Resolution: Force the Strike and Breacher team's to take either 0 drones, 2 tactical drones, or 1 tactical drone and 1 guardian drone.

Cause of Issue: Strike and Breacher teams are the only units in the codex that have optional drones, where it is not listed as "up to".  This was also the case in the index.  The free power level builder they released last week has it correctly limit you to 0 or 2 drones, so it does not appear to be a typo.

**Comment by Mad-Spy** [comment]
The free builder also allows you to take 5 Heavy Weapon teams in a Astra Militarum Infantry Squad, so it's not infallible.

However, it certainly does appear that the datasheet says you have to take 2 drones if you take any.

**Comment by amis92** [comment]
Yeah. The reference to the `Combat Roster` tool is irrelevant, considering that any other unit also has `Drones` increment by 2 - that's because that app only steps by power levels, like you can't take 6 `Fire Warriors`, either 5 or 10 (or 12 for `Strike Team`). Not to mention it actually allows you to take both `Tactical Drones` AND `Tactical Drone & MV36 Guardian Drone`.

As pointed out though, datasheet leaves no doubt. This'll be fixed.
