### ISSUE TITLE
UX Enhancement Summaries

### ISSUE THREAD

**Issue by HarlequinOfDeath** [BSData/wh40k#3062]
File/Catalogue: General
BattleScribe version: 2.01.
Platform: General
Dropbox: No

Description:

I have mentioned this in the Special issue ammunition thread:

All the special rules and especially the special ammunition leads to very long army sheets and gets confusing during matches, especially at tournaments.

Idea: If you look at the Army Builder, for example, the army sheets only show the unit profiles with short summaries of special rules and weapons. And after all the unit profiles there were alphabetical summaries/lists of all special rules and weapon profiles. Would be an awesome option to select in the print roster dialog.

**Comment by amis92** [comment]
Please check out the available output options in BattleScribe. It's quite advanced and elastic since one of the recent updates. If you don't find any combination satisfying, please provide feedback to the author of BattleScribe.

We cannot influence these settings in any way, it's always user's choice. As much as BattleScribe goes, we either provide rules and profiles or don't at all.

**Comment by HarlequinOfDeath** [comment]
Thank you for the response. I will try and contact the author otherwise.
