### ISSUE TITLE
T'au XV107/109 support system fix

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k#3092]
**File/Catalogue:** 
**BattleScribe version:** 2.01.12
**Platform:** Windows
**Dropbox:** No
**Description:

Hello.

1) The cost of support systems on the XV109 should be adjusted to the following values from the T'au Codex:

Shield Generator (all other models): 8pts
Target Lock (all Other models): 6pts
Velocity Tracker (all other models): 2Pts

RAW the current support systems values on BS are specific for Riptide/Stormsurge keywords, which the Y'vahra does not have.

2) XV 107 R'varna should not have the Index Stim Injector, as this was removed per the latest codex FAQ 

Thanks!

**Comment by amis92** [comment]
I don't agree.

1. Imperial Armour Index: Xenos specifies separate points cost for Y'vahra. It isn't marked as `(all other units)` and so isn't updated by Codex.
2. Maybe, but it's not really obvious since it's a direct reference to the wargear, and the FAQ for T'au Codex, is well, for Codex. If it's not enough (although should be since we're talking about Index + Index interaction), please read again the Q and A from FAQ:

> Q: In Index: Xenos 2, the Stimulant Injector was a piece of wargear that I could purchase for certain T’au Empire units. In Codex: T’au Empire, the Stimulant Injector is no longer a wargear option, but instead there is a Stimulant Injector Stratagem. Can I continue to use the Index: Xenos 2 datasheets in order to purchase Stimulant Injectors for my units, as per the ‘What datasheet rules should I use?’ flowchart?
>
> A: No. You cannot purchase Stimulant Injectors anymore and the rules for Stimulant Injectors as presented in Codex: T’au Empire (i.e. the Stratagem) take precedence.


The actual question is **Can I continue to use the Index: Xenos 2 datasheets [...]?**, so RAW it doesn't apply to IAI: Xenos from Forge World.
