### ISSUE TITLE
Orks - Dakkagun Multiples?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3105]
**File:** Orks.catz

**BattleScribe version:** 2.01.18

**Platform:** Android

**Dropbox:** No

**Description:** Nobz on warbikes come with 2 Dakkaguns. But, when you click "view," their weapon loadout is listed as having just one dakkagun.

**Comment by tag8833** [comment]
Hmm.  I think this is due to an issue with the View code.  They definitely have 2 Dakkaguns.   The Dakkagun selection has a min 2 / max 2 constraint on it, and it looks right in roster selection.

I can develop a work-a-round.  Basically embed them in a selection entry that is "2x Dakkaguns"  Should we do that?

**Comment by amis92** [comment]
No, I think that's a similar report to one that I had earlier, that people look at profiles listed instead of selection list.

* When you (by default) have "Minimal output", only optional selections show up in **Selections** for entry. And all profiles. So you see

![image](https://user-images.githubusercontent.com/2671396/40476062-67c9b46a-5f43-11e8-85d7-2d5293bfea19.png)


* The actual "Full output" is completely valid:

![image](https://user-images.githubusercontent.com/2671396/40476108-7fce72d0-5f43-11e8-87ac-829e1cbf7730.png)

---
Embedding them in selection entry that has min=max won't change anything really. You'd have to add a duplicate Profile named "2x Dakkagun", which is pointless.
