### ISSUE TITLE
Chaos - FW Renegade and Heretics: Cannot select any characters as Warlord (plus Chaos Covenant validation error)

### ISSUE THREAD

**Issue by BaconCatBug** [BSData/wh40k#3134]
**File/Catalogue:** Chaos - FW Renegade and Heretics.catz

**BattleScribe version:** 2.01.12

**Platform:** Windows

**Description:** None of the Renegade and Heretics characters can be selected as warlord (since I've noticed only characters in other files get to be selected as warlord despite you being able to make any model your warlord, I assume it's a "No-one actually selects a non-character thus we can save 4 trillion man hours of useless work), which is inconsistent with all other armies.

Furthermore, this means that validation for Chaos Covenant cannot be implemented, since you can only choose a Covenant if your warlord is a Renegade Commander (and then only for the detachment the commander is in), thus you can currently add an Illegal Covenant with no validation error.

**Comment by Mad-Spy** [comment]
You are correct, the Warlord issue needs addressing. R&H Warlords should be able to take BRB warlord traits, so that functionality should be in the catalogue.

You're right that only characters can be selected in catalogues, for exactly the reason you have outlined, and also because only characters can take traits once selected.

Chaos Covenant **is** currently validated. The Roster will give a validation error if you select the Covenant group and do not have a Renegade Commander in your Roster.
![image](https://user-images.githubusercontent.com/29306451/40417467-b92e7574-5e77-11e8-9f38-9c032c03d741.png)

However, when I add the Warlord validation, I'll improve the validation so the Commander also has to be the Warlord.
