### ISSUE TITLE
Imperium - Astra Militarum: Warlord trait validation issue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3145]
**File:** Imperium - Astra Militarum.catz

**BattleScribe version:** 2.01.13

**Platform:** Windows

**Dropbox:** Yes

**Description:** Elite units Platoon commander and Commisars are asked to be given warlord traits even if theres already another warlord (Brigade detachments)

**Comment by CrusherJoe** [comment]
So I'm not sure what's causing this, but every time something like this is reported I try to reproduce and cannot.
![commissar](https://user-images.githubusercontent.com/9998385/40555641-61255a34-600f-11e8-9b68-470523f9c0c8.PNG)
![pc](https://user-images.githubusercontent.com/9998385/40555648-680eadbe-600f-11e8-9a4b-dfa5e2ab831b.PNG)
As you can see from these two images, both units in report are added, and there is no validation error.
![commissar-wlt](https://user-images.githubusercontent.com/9998385/40555667-77d346ce-600f-11e8-9ac4-2a32b1fecc39.PNG)
![commissar-wlt](https://user-images.githubusercontent.com/9998385/40555668-79516da0-600f-11e8-9da1-85a8a60b1cc9.PNG)
As you can see in these screenshots, there IS a validation error, but only after the units in report have been selected as Warlord.

I'd show you that the validation error disappears but there's no difference in the app state from the first two pics.

I mean. I'll make a video if no one believes me, but I cannot trigger a false validation error about Warlord traits with those two units in a Brigade or otherwise.
