### ISSUE TITLE
Leviathan Melee Weapons

### ISSUE THREAD

**Issue by el1l** [BSData/wh40k#3148]
**File/Catalogue:** FW Adeptus Astartes v24

**BattleScribe version:** 2.01.

**Platform:** /iOS

**Dropbox:** Yes/

**Description:**  something is weird with the Leviathan melee weapons.  According to chapter approved:

Claw should be 55 for a single or 65 for pair.
Drill should be 65 for a single or 75 for a pair.

Right now:
 claw is showing as 72 single and 99 pair
Drill is showing 82 single and 109 pair.

It’s also a bit strange how it does it.  In order to get the pair pricing, you need to select one melee weapon... then when you select the 2nd a new price with a ##.5 pt value shows up.  Then you need to go back to the orignal and reselect that to have it update to the matching ##.5 value.

Regardless, In all iterations, the point values are always wrong.

Perhaps there is a way to set the single price as default, and any duplicates show up as only 10pts?

**Comment by Crowbar90** [comment]
Actually, point values are correct, as the pricing you see in Battlescribe includes a 17pts meltagun, which is built-in in the claw/drill. Just subtract those 17pts for a single weapon or 34pts for double weapon and you will get the claw/drill points.

As for the other part of the issue, I agree that it's strange, but that's how Battlescribe works: it revalidates the point cost of an upgrade only when you select it (again). I'd prefer not to change the current behavior since in many cases your proposed solution would cause the same issues, while being less intuitive from the data authors' point of view.

Anyway, thank you for your report and your suggestion!
