### ISSUE TITLE
Missing units for Death Guard

### ISSUE THREAD

**Issue by devonjones** [BSData/wh40k#3201]
**File/Catalogue:** Chaos - Death Guard.cat

**BattleScribe version:** 2.01.19

**Platform:** Android

**Dropbox:** No

**Description:** Detailed issue description.

Death Guard are missing the following units (From Imperial Armor Index Forces of Chaos):

**Death guard specifically:**
Greater Bloat Drone
Necrosius The Undying

**General chaos stuff that Death Guard can take:**
Chaos Decimator
Hellforged Contemptor Dreadnought
Hellforged Land Raider Proteus
Hellforged Land Raider Achilles
Hellforged Predator
Hellforged Scorpius
Hellforged Sicaran
Hellforged Sicaran Venator
Hellforged Spartan Assault Tank
Hellforged Deredeo Dreadnought
Hellforged Leviathan Dreadnought
Hellforged Dreadclaw Drop Pod
Hellforged Kharybdis Assault Claw
Hellforged Cerberus Heavy Destroyer
Hellforged Typhon Heavy Siege Tank
Hellforged Fellblade
Hellforged Falchion
Hellforged Mastodon
Chaos Hell Blade
Chaos Hell Talon
Chaos Storm Eagle Assault Gunship
Chaos Fire Raptor Assault Gunship
Chaos Thunderhawk Assault Gunship
Chaos Sokar Pattern Stormbird Gunship
Chaos Xiphon Interceptor

**From the Imperial Armor Index Forces of Chaos 1.2**

FAQs
Q: Are there any restrictions on which Legion I can choose when replacing the <Legion> Faction Keyword on datasheets within this book?
A: Yes, as follows:

-Snip-

You can only choose for a unit to be from the Death Guard Legion if it has the Nurgle keyword, or if it
has the <Mark of Chaos> keyword and you choose to replace that with Nurgle. You cannot choose for a Hellforged Rapier Battery, a Chaos Hellwright or a Chaos Hellwright on Dark Abeyant to be from the Death Guard.

-Snip-

Worth noting, there are probably similarly missing units for Emperor's Children, Thousand Sons and World Eaters

**Comment by alphalas** [comment]
They’re not missing, they’re in the FW chaos cat.

The reason why is because the units are all the same for CSM/TSons/DG, so duplicating that whole cat 3 times would actually almost triple the size of the TSons cat and the DG cat, and double the size of the CSM cat, causing dramatic performance degradation with only minor convenience increases. 

With all the Chaos cats, if you include a child detachment of the FW cat, you’ll have all the units in one list, without the needless performance degradation.
