### ISSUE TITLE
Imperium - Blood Angels: Validation error on Lieutenant

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3258]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.18

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** When Lt. takes jump pack, forces error on mc boltgun

**Comment by Mad-Spy** [comment]
I'm unable to reproduce this error in Blood Angels v44. Selecting a Jump Pack on a Lieutenant gives no validation error.

The only way I can generate an error on the Master-crafted boltgun group is to add a new weapon without unchecking the boltgun itself.

**Comment by vonblinden22** [comment]
What I'm saying is, when you choose the jump pack for the Lieutenant, and then one weapon from the melee weapons list, and leave the Master Crafted Boltgun checked, (because you need to if you're keeping it, and to keep the points cost correct), the orange eye that shows there is an error lights up, and then says that Lieutenant has one too many selection from Master Crafted Boltgun.

**Comment by vonblinden22** [comment]
Just realized that Jump Pack has nothing to do with it. If you choose a different weapon other than Chainsword from the Melee weapons list, it produces the error on the MCBG.
Lieutenant should be able to retain the MCBG whilst still trading CCW for something else, I am fairly certain.

**Comment by vonblinden22** [comment]
As a point, Gentlemen, I'd personally like to thank all of you for all your hard work on keeping that craziness up to date! I just thought I'd let you guys know about that.
