### ISSUE TITLE
Add Super-Heavy Deatachment with no command Benefits for Imperial Knights

### ISSUE THREAD

**Issue by p12om3th3us** [BSData/wh40k#3278]
Imperial Knight codex allows Super-Heavy Detachment for Knights with Armigers but with no command benefits much like the unique assassin vanguard  detachments. This is not reflected in the current 40k battler-scribe for Ipad.

**Comment by Kohato** [comment]
So, the issue with this is more a BS issue than a cat issue.  The Assassins cat adds a duplicate Vanguard force type that doesn't have "+1CP" at the end of the name.  That Force does not have an HQ slot, so it works well.

I can't however, bar only Armigers from being selected in a LOW Slot.  It works for Assassins since there simply is no HQs.

There are two options I see to support this rule:

1) Add a duplicate force named "Super Heavy Detachment" akin to the Vanguard duplicate that requires less than 3 Questoris/Dominus Class knights. And then require 3 or more Questoris/Dominus in the normal Super Heavy.

2) Add a Rule called "Knight Lance" that hides if not a Super Heavy Force that explains the CP Reduction with Armigers.

Option 1 is messy as all hell and will end up rather confusing to users.  I say this because of history of tickets received and confusion over other messy implementations.

Option 2 leaves the validation to the player.  This option is preferred however and is actually already present in the cat (however I had a condition flipped wrong and the rule was actually hidden in only super heavy detachments, instead of shown in only super heavy detachments).  We do not track CP in any sort of counter in BS and there are a myriad of other situations that modify total CP count that we do not track.

I will be implementing Option 2 by correcting the faulty conditional I have already set in there.
