### ISSUE TITLE
Imperium - Deathwatch - Chaplain in power armour has access to Terminator Combi-Weapons

### ISSUE THREAD

**Issue by FarseerVeraenthis** [BSData/wh40k#3315]
When selecting a Chaplain in power armour, he comes equipped with a Crozius and a Storm Bolter from the Terminator Combi-Weapons list.
He shouldn't have access to this list while wearing Power Armour, and his default gun should be a Bolt Pistol.
Also, I'm not sure he actually should be allowed access to a standard Boltgun, but that might be an Index issue...

**Comment by acebaur** [comment]
You're partially right. He shouldn't have the TDA combi weapons in his weapon selection, but he does have access to both a boltgun and the combi weapon list via the Index. I'm not sure who changed this because the last revision I did it was correct. Anyway, I've created a branch and will fix it shortly

**Comment by FarseerVeraenthis** [comment]
Yeah, that's cool, my ePub reader was giving me trouble last night so I couldn't check properly. 
In that case, the bolt gun and combi weapon options should really be flagged "index" :smile:

**Comment by FarseerVeraenthis** [comment]
closed by #3316
