### ISSUE TITLE
Imperium - Space Marines: Devastator Sergeant should not be able to unselect bolt pistol.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3388]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** The options for the Devastator Sergeant are incorrect. In the Codex, the Options tab says "The Space Marine Sergeant may replace his boltgun with items from the Sergeant Equipment list". However, the options tab for the Devastator Sergeant allows you to replace the bolt pistol as well. However, this is not an issue for the Blood Angels and Dark Angels, as those armies only allow you to replace the boltgun on Devastator Sergeants. The options tab in the app should have the bolt pistol as a permanent option, and should only allow the Boltgun to be replaced (i.e, you can have a Sergeant with a Bolt Pistol & Chainsword, or a Bolt Pistol and Combi-Flamer, but not be able to take, for example, a Combi-Flamer & a Chainsword).

**Comment by Mad-Spy** [comment]
Something odd is going on, as the Dev Sergeant currently has 2 bolt pistols. Looks like something got re-implemented and no special exception was made for the Dev Sergeant.

**Comment by Wulfyn** [comment]
This bug report has a correct title but an incorrect description. The line for the Devastator Sergeant reads: "The Space Marine Sergeant may replace his boltgun with items from the Sergeant Equipment list". That's items, not "an item" as you see with many other sergeants (for example the Assault Squad Sergeant reads "The Space Marine Sergeant may replace his bolt pistol with an item from the Melee Weapons or Pistols list" - which would mean a single item).

As the Devastator Sergeant is allowed to take multiple items the description in the bug report that they are not allowed a Combi-Flamer and a Chainsword is incorrect. The Boltgun can be replaced by multiple items because it specifically states "items" not "an item".
