### ISSUE TITLE
Dark Angels : Wrong cost for Thunder Hammer on Lieutenants

### ISSUE THREAD

**Issue by AurelHugon** [BSData/wh40k#3404]
**File/Catalogue:** Warhammer 40,000 v1.1.56

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** 
Wrong point costs on the Thunder Hammer for Dark Angels Lieutenant.
The point cost in the App is 16pts;
It should be 21points.

**Comment by williamcaw** [comment]
https://github.com/BSData/wh40k/issues/3415 duplicate

**Comment by Mad-Spy** [comment]
@Thairne, I had a look at this, but I can't find a nice way to implement it with the current way weapons are set up on the Lieutenants. The nesting is stopping the modifier on the TH from picking up that the model is a CHARACTER. It either needs the weapons redoing, or the keywords moved down to be on the model level rather than the unit.
