### ISSUE TITLE
Imperium - Space Marines - Intercessor Sergeant missing options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3408]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** Updated 16/04/2018
CODEX: SPACE MARINES
Official Update Version 1.2

Page 148 – Intercessor Squad, Wargear Options
Change the third bullet point to read:
‘The Intercessor Sergeant may either replace their
bolt rifle with a power sword, or take a power sword in
addition to their other weapons.

missing equipment on 
Intercessor Squad
bolt rifle options

**Comment by Mad-Spy** [comment]
The whole squad has to change weapons, so the weapon choice is made at the squad level. You can't swap weapons on an individual basis.

**Comment by williamcaw** [comment]
ya i don't see Sargent being able to have a gun at all. he has the pistol but not the rifle section.

**Comment by Mad-Spy** [comment]
The gun selection is made and paid for at the unit level. The individual models _don't_ have a rifle entry, on either the standard Intercessors _or_ the Sgt.

**Comment by williamcaw** [comment]
Unit: Intercessor Sergeant, Weapon: Bolt pistol, Frag grenade, Krak grenade are the only weapon on him. the squad is only counting 4 for the bolt rifles, auto bolt rifle and the stalker bolt rifle is one item but not applying to the Sgt or squad at all either

**Comment by Mad-Spy** [comment]
Yes, that's correct. There is no entry on the models for the rifle because it is purchased at the squad level.

It's easier to see what I mean if you switch the unit over to Stalkers, because the single rifle entry (which is counted at the Squad level) will move to the bottom of the entry and cost 2pts per model (including the Sgt.)

![image](https://user-images.githubusercontent.com/29306451/43845200-5b40976a-9b23-11e8-831d-d1f239e9e206.png)
