### ISSUE TITLE
Merge Astra Telephatica and Sisters of Silence files

### ISSUE THREAD

**Issue by Viper666-Qc** [BSData/wh40k#3417]
Why keeping them separated? The Sisters of Silence have the Astra Telepathica  
faction keyword.

**Comment by alphalas** [comment]
Because they are separate factions, as exemplified in Index:Imp2, and the fact that in the Big FAQ they had to create a unique detachment for SOS; the army has no HQs. Combining the two cats is not an option.

**Comment by alphalas** [comment]
To Counter the point you brought up of they both have the AAT keyword: you are correct, they do. However, all the faction AAT units *ALSO* have the Astra Milirarum keyword. Same with Uriah Jacobus, he’s a Ministorum character who also has Astra Militarum keyword. Organizing cats by keyword, instead of set army lists according to the source material is a rabbithole that will produce endless headaches for us the data devs and users alike.

**Comment by alphalas** [comment]
It you look at how the Index:Imp2 is laid out, there are factions and subfactions. Example is AdMech; AdMech is the faction, and Cult Mech and skittari are subfactions. Each is separated out by a fluff blurb at the beginning, but only AdMech has a “Army list” and “wargear list” laid out that covers both subfactions. AAT and SoS both have their own “army list” and “wargear list” sections, Independant of each other.
