### ISSUE TITLE
no warlord trait on Canis

### ISSUE THREAD

**Issue by blackflow** [BSData/wh40k#3502]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** No

**Description:** Selecting Canis as your warlord dosen't let you select warlord trait.
Also I think he should be able to take a relic.

**Comment by Mad-Spy** [comment]
You can't choose a warlord trait for named characters (it's usually fixed) or give them relics.

**Comment by Kohato** [comment]
So as Will and Iain said, No relics - he's a named character.  That is consistent across all of 40k.

I'll fix the missing WT's when selecting him as Warlord, don't know how I missed that.

Here's the kicker though, I think he'd be able to choose his own WT if he was the target of exalted court ... wouldn't he? Since he's not the warlord, he doesn't get the pre-set traits.

**Comment by blackflow** [comment]
Yup, my bad with the relic, and yes Canis can only have the Wolfkin Saga only if he's a warlord.

**Comment by Kohato** [comment]
Well ... This is awkward - we thought you meant Canis Rex, from IK (Which there actually is an issue lol).  So to confirm - there's no issue with SW's canis?

**Comment by blackflow** [comment]
Ok, now I see the tag. I was talking about Canis Wolfborn - in the new update you can select him as a warlord but can't select hist trait (although as I said, it should be auto added since he can have only one)

**Comment by CrusherJoe** [comment]
This is fixed in v46 of the datafile.
