### ISSUE TITLE
Imperium - Deathwatch: Watch Captain equipment issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3549]
**File:** Imperium - Deathwatch.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** Deathwatch Watch Captain wargear options not working properly.
Selecting a Chainsword replacement (e.g. ligtning claw) and master-crafted boltgun yields invalid roster.
Similarly it is not possible to (validly) select Relic blade and Storm shield (though Thunder hammer and Storm shield combo is valid).

**Comment by Mad-Spy** [comment]
You cannot have a master-crafted boltgun if you choose to take any items from the Deathwatch Equipment list (such as a Lightning Claw). You have to give up both the chainsword and gun.

![image](https://user-images.githubusercontent.com/29306451/45153461-f6afe480-b1cb-11e8-8ae2-c965b377e187.png)

This also why you can't do Relic Blade/SS, because it would require you to swap the chainsword and MC boltgun for equipment list options, which leaves you unable to swap the chainsword again for a relic blade, _even if_ you choose a chainsword from the list.

Stupid, but true.

**Comment by Mad-Spy** [comment]
On re-reading the Index, you should be able to do the master-crafted boltgun and a replacement melee weapon (but not relic blade or SS), so this is incorrect in the datafile.

**Comment by blazoncek** [comment]
Thanks for clarifying.
Yet, no wording can prohibit swapping MCB/CS with SS/CS 1st and then swapping CS with relic blade.
So this would allow SS/Relic blade option. IMO

**Comment by WindstormSCR** [comment]
The original designer commentary prohibited double-swaps, and so does the precedent applying to deathwatch terminators (cyclone/sb > swap sb prohibited in the general case)

**Comment by williamcaw** [comment]
There was a faq about this  character

**Comment by WindstormSCR** [comment]
So, this is a "won'tfix" because the logic for this already exists, simply take the option you want from "melee weapons (Index)" as you are using index logic, and it will not throw an error. the only case that will throw an error is pulling from the deathwatch equipment list.
