### ISSUE TITLE
Imperium - Grey Knights Inconistent Relic Behaviour

### ISSUE THREAD

**Issue by someguyss** [BSData/wh40k#3594]
**File/Catalogue:** Imperium - Grey Knights.catz

**BattleScribe version:** 2.01.15.114

**Platform:** Linux

**Dropbox:** No

**Description:** The Relics menu should be hidden until either a Warlord is assigned or Armoury of Titan is selected (consistent with the behaviour of relics across the rest of the 40k armies). Currently it's always visible and simply throws an error if you pick one anyway.

**Comment by tekton** [comment]
I understand where you're coming from, but the feedback has been that it's more helpful to see them before said things are checked off. Additionally, not all armies have that hidden, the Custodes also have them visible from the beginning; again due to previous feedback that its more helpful for elite armies.
