### ISSUE TITLE
Imperium - Space Marines: Scout sergeant must take Bolt pistol from the Weapon Options

### ISSUE THREAD

**Issue by Guy-Markman** [BSData/wh40k#3783]
**File/Catalogue:** Imperium - Space Marine

**BattleScribe version:** 2.01.19

**Platform:** iOS

**Dropbox:** No

**Description:** When I try to change the gear for scout sergeant from bolt pistol from the Weapons Options, I get two different errors.

For example, if I take scout Sergeant with sniper rifle and chainsword, I’ll get this errors:
“Scout Sergeant must have 1 more selection from Sgt Equipment (minimum 2)”
and
“Scout Sergeant has 1 too many selections of sniper rifle (maximum 0)”

even if I’ll take bolt pistol from the Sgt Equipment I’ll get this errors.

**Comment by Guy-Markman** [comment]
Also will happens if I’ll switch the sniper rifle for Boltgun, shotgun and Combat knife. 
Also if I’ll take a pistol from the Weapons options and any item from the Sgt Equipment it will still happens.

**Comment by Mad-Spy** [comment]
You cannot give a Scout Sergeant a Sniper rifle _and_ a chainsword. In order to access the _Sergeant Equipment_ list and get a chainsword, you must replace both the bolter __and__ bolt pistol, as per the first bullet point. Once you have done so, you can only select from the _Sergeant Equipment_ list, which does not include the sniper rifle.

**Comment by ChadMichels** [comment]
If you take any items from the Sgt Equipment list, you must take two items from the Sgt equipment list, agreed per bullet point one.
But then I can re-take a bolt gun from the Sgt equipment list, and then why can I not replace it with a sniper rifle per bullet point three? 

I could argue either way, is there a ruling on this?

**Comment by Mad-Spy** [comment]
You're right, it can be argued either way. 

GW themselves have made specific rulings both ways. DW Watch Captains cannot swap replacement wargear per their FAQ, but Wolf Guard Terminators can per their FAQ.

Probably worth an email to the FAQ Team to try and get this cleared up.

**Comment by Guy-Markman** [comment]
I’ll send a message to GW on Facebook and’ll see their response.

**Comment by ChadMichels** [comment]
FYI, just as a point of reference:
I realize the datasheets are not exactly the same, but the 'newer' Space Marine chapeter codexes, Dark Angels, Blood Angels, the Scount Sgt is definitly able to take a Sniper Rifle and Chainsword.  

I can't imagine why this would be intentional, other than the generic Space Marine codex allowing those Scount Sergent's chapters access to the Sgt Equipment list, which includes the combi weapons, whereas the melee and pistol lists do not include those.  (This also feels more like an oversight than anything else.)

**Comment by Guy-Markman** [comment]
The Facebook team couldn’t give me an answer

**Comment by Mad-Spy** [comment]
I think, on balance, and given that all newer Codexes allow this option, that the vanilla SM should allow it too, so I've changed it back.
