### ISSUE TITLE
Orks: Upgrade to da new WAAAAAAGH!

### ISSUE THREAD

**Issue by Eonfuzz** [BSData/wh40k#3801]
Hey crew, I've gone ahead and made a bscribe file for the new Ork Codex.

https://github.com/Eonfuzz/ork-prerelease
It'll need a bit of polish (Power levels, and names of relics) but they're unknown until release.

Hopefully this'll cut down on the work you gotta do, feel free to use it

**Comment by tag8833** [comment]
I've got one at a slightly more complete level on my branch:  
https://github.com/BSData/wh40k/tree/Ork_Codex_WIP

But I did grab your list of warlord traits and relics.  You did a good job with the file, and if mine weren't already so far along, I definitely would have started from your version.  

One thing I still need to implement is the restrictions on the relics.  For instance "Painboyz only" or "Replaces a unit's Power Klaw"

**Comment by GenWilhelm** [comment]
Gave the file a once-over (except for the Gunwagon and Bonebreaka, since they clearly weren't finished), and here's what I found:
- [ ] There should be a way to create a detachment with units from different clans (e.g. Ghazghkull and Snikrot).
- [ ] Badrukk should be able to be included in any detachment without affecting their Kultur.
- [ ] Named characters should be forced to take their clan's Warlord Trait.
- [ ] (Big) Meks - (Big) Mekaniak - Not longer has the restriction on units that FLY.
- [ ] Boss Snikrot - Terrifying Killer - Subtracts 1 from Ld, rather than adding 1 to Morale.
- [ ] Deffkilla Wartrike - Shouldn't have the Breakin' Heads ability.
- [ ] Kaptin Badrukk - Should be S5.
- [ ] Boyz - Should they have a selection for 'ard boyz or skarboyz?
- [ ] Boyz / Warbikers - Boss Nob - Should have access to the new Nob Weapons wargear list.
- [ ] Mad Dok Grotsnik - Should appear for Deathskulls Kultur, instead of Goffs.
- [ ] Nobz - Should have access to the new Nob Weapons wargear list.
- [ ] Megatrukk Scrapjet / Rukkatrukk Squigbuggy - Should have the Explodes ability.
- [ ] Mek Gunz - No longer has the Artillery ability.
- [ ] Mek Gunz - Mek Gunz and Grot Krew are now two separate abilities.
- [ ] Killa Kans - Should be 7 PL for 2-3 models, and 14 PL for 4+.
- [ ] Deff Dreads - Should be 5 PL for 1 model.
- [ ] Stompa - Bigger 'n' Stompier - Should be able to move over SWARMS as well as INFANTRY.
- [ ] Mekboy Workshop - Should be 4 PL.

**Comment by WarlordWossman** [comment]
> Mad Dok Grotsnik - Should appear for Deathskulls Kultur, instead of Goffs.

Should doublecheck this with the codex, I am pretty sure they changed him to goffs at some point.

**Comment by tag8833** [comment]
Last codex changed him to Goffs.  This one changes him back.

**Comment by tag8833** [comment]
My Branch is updated with the rest of the fixes.

**Comment by tag8833** [comment]
Merged into Master.  A release is planned.
