### ISSUE TITLE
Avenger not in Adepta Sororitas army list

### ISSUE THREAD

**Issue by Aquilanus** [BSData/wh40k#3808]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

**Comment by Aquilanus** [comment]
Hello. I was hoping someone could add in the Avenger to the Ministorum list? Thank you. If it helps I can help out with the Avengers profile etc.

**Comment by GenWilhelm** [comment]
Which Avenger do you mean; the strike fighter, or another one?

If it's the strike fighter, it doesn't have the ADEPTUS MINISTORUM keyword, and is therefore not included in that catalogue. You'd have to either take a separate detachment of Astra Militarum, or create a multi-catalogue detachment in order to include them with the Ministorum:
https://github.com/BSData/wh40k/wiki/Creating-Detachments-Using-Multiple-Factions

**Comment by Aquilanus** [comment]
I could have sworn it had the Ministorum keyword :( I'll try the link you posted to get around it.

Thanks ^_^
