### ISSUE TITLE
Orks.Catz Problems 

### ISSUE THREAD

**Issue by LIBEDRAT0R** [BSData/wh40k#3813]
**File/Catalogue:** Orks.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** No

**Description:** 
1. Boss Nobs can only get a slugga and kombis from the shooty items. Please add the Index options like the kustom shoota too. 
2. Bonebreaker can get unlimited number of Bonebreaker Rams. 
3. gitstoppa shells has a typo "imrpove" instead of improve.
4. index option says that each nob can get an ammo runt. It only allows me for a single runt to be taken, maybe its a codex thingy am not sure. Can we have both options?
5. Runtherds are placed in the "No Force Org Slot". 
6. mekboy workshop has plenty of typos

**Comment by tag8833** [comment]
1. I'm adding the index option of shoota to arm one.
2. Fixed
3. Fixed
4. I'm not sure how to handle that one.   Codex says 1 per 5.  Index says 1 per.  It's still an option, just a more limited one.  My inclination is to go with the codex on this, but I'll run it by the other data authors to get their thoughts.
5. That is their rules in the codex.  It's even a rule I typed up on that unit.
6.  That is a lot of text for rules that nobody will ever use, but I've fix it.  At least someone can probably read the rules, and figure out why they would never pay points for that model.

**Comment by LIBEDRAT0R** [comment]
thank you :)

**Comment by LIBEDRAT0R** [comment]
still no kustom shoota in boss nobs

**Comment by tag8833** [comment]
On it.   I added the normal shoota.  I'll check the index to see if there is anything else I left off.

**Comment by tag8833** [comment]
Regarding ammo runts.  It seems like the Index wargear options are protected via the FAQ, but since the Ammo Runts were part of the unit composition in the Index they aren't covered by the FAQ, and thus are no longer available beyond the ones you can get from the codex as part of the wargear selection.

I'm closing this item for now, if you think that I haven't understood the FAQ appropiately, feel free to open a new issue.
