### ISSUE TITLE
Orks: Morgarg's Finkin' Cap Trait Selection

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#3839]
**File:** Orks.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** If you take two traits to the warlord with Blood Axes relic Morgarg's Finkin' Cap give error despite it possible make it

**Comment by tag8833** [comment]
On it.

**Comment by jimonmars** [comment]
This is not fixed.  You still cannot take two warlord traits without error.

**Comment by tag8833** [comment]
We pushed a release today that contains that fix:
https://github.com/BSData/wh40k/releases/tag/v1.1.73

Update your data, and it should work.

**Comment by jimonmars** [comment]
Nope.  Not fixed.  Have you tried it?

**Comment by tag8833** [comment]
Oh, so I completely missed the goal, and didn't even consider that approach.  You want 2 warlord traits on the same model.  I thought you wanted 2 warlord traits in the same roster which is what I fixed.  2 Warlord traits on the same model was outside the realm of my imagination.  

I think it is a super easy fix, though fixing it is going to mean that warlord traits are always checkboxes instead of radio buttons.  Let me play around with it, because I really like warlord traits to be radio buttons in most cases.  I'll try to have an update for this later today.

**Comment by tag8833** [comment]
I made this fix to our WIP.  I'll be pushing a release shortly.  Hopefully you will have it if you update your data tomorrow.

**Comment by jimonmars** [comment]
Just grabbed Ork V32.  I see how it works, instead of checkboxes it has a separate page of the same traits.  That works very nicely!

Tested trying to select the same one in both lists, which generates the warning, as expected.

Nice elegant solution, thanks!
