### ISSUE TITLE
Chaos - Daemons: Characters missing relics options

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4458]
**File:** Chaos - Daemons.catz

**BattleScribe version:** 2.01.15

**Platform:** Windows

**Dropbox:** Yes

**Description:** Missing warlord options from herald on chariots, steed, infernal enchantress as are the relics of chaos options. Same is present on the android data files

**Comment by Mad-Spy** [comment]
These are missing from the Enrapturess, but are present on the other Heralds if a DAEMONS Warlord, or a Relic Stratagem choice are made.

**Comment by raven1840** [comment]
Also missing from herald under relics: 
SLOTHFUL CLAWS
.
SLAANESH HERALD only. 

The slothful claws replace the bearer’s ravaging claws and has the following profile:
WEAPON RANGE TYPE S AP D
Slothful Claws Melee Melee +1 -2 2
Abilities: Each time you make a wound roll of 4+ for this weapon, that hit is resolved with a AP of -4 instead of -2.

**Comment by Mad-Spy** [comment]
Which Herald? The Index Heralds do not have Ravaging Claws, so they are not eligible to take them. They are available for both the Codex Herald, and as of me fixing this, the Enrapturess.
