### ISSUE TITLE
Deathwatch Watch Captain

### ISSUE THREAD

**Issue by bendjlee** [BSData/wh40k#4462]
**File/Catalogue:** 
Death Watch
**BattleScribe version:** 2.01.

**Platform:** Android

**Dropbox:** Yes

**Description:** Detailed issue description.
Terminator Watch Captain is missing Auxiliary Grenade Launcher (as per Index Imperium 1 | Watch Captain in terminator armour takes on the Datasheet from the terminator captain)

Watch Captain is able to replace both his "Chainsword & Master Crafted Boltgun" for two weapons from Deathwatch Equipment list - Error is thrown when you try to equip him with a second bolt pistol.

**Comment by WindstormSCR** [comment]
There is a lot of ambiguity about the thing deathwatch can and cannot take from the index, and there have been several reviews of what is and isn't valid to be taken because of the snarl of rules and interactions governing that datasheet, and where it stands now is as close to RAW as we can stand.

Watch captain is a simple shared fix for bolt pistol and will be fixed in next release
