### ISSUE TITLE
Grey Knights: Techmarine Wargear?

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#4681]
**File/Catalogue:** Grey Knights v31

**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** No

**Description:** I appreciate the inclusion of index wargear options for the GK Techmarine. I may have found a few slight issues with the current configuration.

1. On pg. 181 of the Imperium 1 Index it states that GK Techmarines _must_ take a servo-harness. Then, the datasheet for the Index Techmarine states that if it takes a servo-harness "neither servo-arm may be replaced with a conversion beamer" (pg. 16).

So if I'm understanding correctly, given the GW flowchart, the "Index version for its wargear options" would not allow GK techmarine to ever take a Conversion beamer or drop its additional Servo Arm.

2. Shouldn't the GK Techmarine have further options to replace it's Bolt Pistol with a gun from the Pistols or Combi-Weapons lists, as described in the Index?

Thank you!

**Comment by DrTobogganMD** [comment]
Correct, the wargear on a GK Techmarine in the codex presumes a Servo Harness is present.

The only options present on a TK Techmarine should be:

1) Boltgun > Bolt Pistol
2) Power Axe > Melee Weapon List
3) Depending on who you ask, Bolt gun > Bolt Pistol > Pistol/Combi-Weapon lists.  (Since codex doesn't have a pistol by default, can you swap, then swap again?)

**Comment by tekton** [comment]
I added the servo arms option because people kept asking for it and a certain writer mentioned it was ok as technically that's what they meant at LVO- it's why it clearly calls it out as Index vs Codex, but I'll go back and clean it up later.

I swear it already allowed the combi-pistols...stupid editor
