### ISSUE TITLE
Chaos - Chaos Space Marines: Master of Possession issues

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4738]
**File:** Chaos - Chaos Space Marines.catz

**BattleScribe version:** 2.01.15

**Platform:** Mac

**Dropbox:** Yes

**Description:** Hey there, 
I found 2 bugs with the Master of Possession in the new Shadowspear box:
1) He can take the Mark of Chaos, which is important since for example with the mark of slaanesh he has access to psychic powers like "delightful agony".
2) currently world Eater have access to him, which is not possible, since they can not have any psyker  in their legion. 

Thanks you for your work :)

**Comment by Mad-Spy** [comment]
1. You're correct that he should be able to choose a Mark, however, he cannot choose the Mark-based powers.. Those powers are in the Dark Hereticus Discipline, not Malefic. As per the rules on p161 of Codex: CSM:

> MARK OF CHAOS PSYCHIC POWERS
> A <MARK OF CHAOS> PSYKER that can use powers from the Dark Hereticus discipline can replace one of its Dark Hereticus powers with the appropriate <MARK OF CHAOS> psychic power on the right.

The above clearly states that you need access to Dark Hereticus in order to take the <MARK OF CHAOS> power.

2. Fixed.
