### ISSUE TITLE
Imperium - Blood Angels: Hand flamer statline incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4872]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.01.24

**Platform:** Android

**Dropbox:** No

**Description:** Incorrect type for hand flamer weapon. Hand flamer is currently type: pistol D3, but it should be pistol D6 as stated in Chapter Approved 2018.

**Comment by Mad-Spy** [comment]
There have been no Errata released changing the profile of this weapon for Blood Angels. Although CA2018 does say that they will be updating the profile, it hasn't happened yet, because the Sisters rules are still in beta. As soon as an Errata is released updating the profile, we'll update it in the files.
