### ISSUE TITLE
T'au Empire: IA Tanks using wrong cost for smart missiles?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#4891]
**File:** T'au Empire.catz

**BattleScribe version:** 2.01.17

**Platform:** Windows

**Dropbox:** No

**Description:** The Smart Missiles weapon for the TX7 Fire Support Hammerhead and TX7 Heavy Bombardment Hammerhead has a cost of 30 points (15 each) but this is the Codex cost of that weapon, as Forgeworld Index tanks they should use Forgeworld points costs which is 20 points per system, 40 points overall.

**Comment by williamcaw** [comment]
This was updated in chapter approved.

**Comment by williamcaw** [comment]
It’s was updated in chapter approved 2017

**Comment by DrTobogganMD** [comment]
@williamcaw That is incorrect. Please stop reposting that.  OP Is correct, FW Xenos 1 states points at 20 and that has never been updated in CA.

**Comment by amis92** [comment]
I disagree. For a single Faction, there is only ever one *latest* publication with the *latest* point cost for a given unit or wargear.

Which means, in a given catalogue, there should only ever be a single point cost for a given wargear. And so it happens that an item like SMS had it's point costs updated several times.

Unless proven otherwise, I'll follow rules of "latest published", of which an example is this header from Chapter Approved 2017, Forge World section:

![image](https://user-images.githubusercontent.com/2671396/55710078-13bec700-59ea-11e9-8871-e82d9e64f354.png)


Please note especially the last sentence:

> If a unit or item of wargear does not appear in any of the tables below, continue to use the points values for it that are listed within the most recently published datasheet for that Faction.
