### ISSUE TITLE
2.02 enhancements

### ISSUE THREAD

**Issue by amis92** [BSData/wh40k#4977]
With the BattleScribe v2.02 unleashed, we have some new features to use. Let's explore them and make a list of possible an/or suggested enhancements/refactorings we can do.

1. Catalogues can now be imported into other Catalogues using Catalogue Link elements. This allows sharing of elements between multiple Catalogues.
2. Catalogues can be marked as a "library." Library Catalogues are only used for importing into other Catalogues. They are not listed when creating a Roster.
3. New "Primary Catalogue" query scope allows Conditions to check whether an Entry has been imported into a particular Catalogue.
4. Entry Links can now contain child Selection Entries, Selection Entry Groups and Entry Links.
5. New Modifier Group element which can contain multiple Modifiers and Modifier Groups which are all applied together according to a single set of Conditions.
6. New Info Group element which can contain multiple Rules and Profiles along with Modifiers for the entire Group.
7. New Publication root element replaces the book field. Child elements select a publication via a drop-down.
8. All "Entry" elements can now contain Rules, Profiles, Info Groups and Info Links for improved consistency.
9. Characteristic values are now XML text elements meaning formatting should work properly.
10. Unneeded empty XML tags are no longer written to files when saving.

---
Most impacting are: 1,2 (libraries) and associated with it is 3
Dev-life betterment: 4,5,6,8 will allow a better organization of modifiers with conditions, and rules and profiles.
UX betterment: 7,9
Memory footprint and git diffs: 10

**Comment by amis92** [comment]
The big one I see is to unify Publications, where necessary elevate them to GST and finally have some consistency with naming of our sources. Probably should be initially done by everyone separately in catalogues, and then where appropriate unified with and elevated to GST.

**Comment by GenWilhelm** [comment]
With libraries being a thing, we should try to trim as much stuff out of the GST as we can.

An "Astartes" library would probably cover most of it.

**Comment by Thairne** [comment]
as well as most common stuff like tactical marines.
Would also unify UX and UI across cats that use them where applicable.
SW are out of luck, but especially stuff like Phobos could be outsourced since they do not differ at all.

Will cause some more work for certain cats to unify the UX to match the imported ones, but that is par for the course.

**Comment by WindstormSCR** [comment]
Unfortunately we are missing core functionality needed to pull entire units to libraries at this time. the most important being ability to modify non-local shared entries (library/gst entries) to set things such as categories/keywords, and publication specific alterations.

By way of example: tactical marines would need Blood Angels instead of <chapter> and a way to add heavy flamers to the options list, both currently not doable to non-local shares

**Comment by GenWilhelm** [comment]
The categories can be set on the root link, and can the Heavy Flamer not be hidden with a Parent Catalogue condition?

**Comment by williamcaw** [comment]
Ther is a  candidate for one new features  #2445

**Comment by bguyan** [comment]
Hey, I cant seem to find the wh40k data in bs2. i tried on my phone and desktop but it doesnt list it as a data source, do i need to clone the repo and do something with it to get it to work?

**Comment by amis92** [comment]
We're continuing major work in #7063 for Astartes libraries/separation, and in #5233 for publications cleanup.
