### ISSUE TITLE
Bug: Astra Militarum - Ministorum Priest's Inferno Pistol has incorrect points cost

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#5035]
**File/Catalogue:** Astra Militarum v210

**BattleScribe version:** 2.02.01

**Platform:** Windows

**Dropbox:** No

**Description:** The Ministorum Priest's Inferno Pistol was reduced to 7 points in Chapter Approved 2018. Even when using the Use Beta Rules option, the cost is still at 9 points.

**Comment by Mad-Spy** [comment]
Can you provide reference for this? The Ministorum Priest does not appear in the beta Sisters Codex, and the Inferno Pistol points were not amended for Astra Militarum units, so I do not see how his pistol would be cheaper.

**Comment by Dunamis55** [comment]
1. The Ministorum Priest is listed in Imperial Index 2, where he's listed with the Adeptus Ministorum army and has the wargear option to take an Inferno Pistol.
2. The Ministorum Priest also has the Astra Militarum faction keyword, so is listed in the Astra Militarum Codex, where he still has the Adeptus Ministorum faction key, but the option to take an Inferno Pistol is not mentioned in the AM Codex.
3. There is no listing anywhere for an Inferno Pistol in Astra Militarum points costs in any book.
4. The Inferno Pistol cost in the Adeptus Ministorum points values list in Imperial Index 2 is 9 points.
5. Adeptus Ministorum models are included in the Beta Codex for the Adeptus Sororitas, and in that points list, the Inferno Pistol costs 7 points.

To me, the Ministorum Priest would use the updated points cost from the Beta Codex in Chapter Approved 2018, as he's an Adeptus Ministorum model that can also be taken in the Astra Militarium army. This is further reinforced by the fact that the Preacher and Missionary units have the Ministorum Priest keyword (although they don't have the Astra Militarum faction keyword).

**Comment by WindstormSCR** [comment]
Yay, priests leading the way into uncharted RAW....again

**Comment by Nokhal** [comment]
>uncharted RAW....again
Not uncharted. Just apply it slowly word by word using the good ol' designer commentary chart. 
The beta Codex is a codex by itself, with it's own point value in a clearly separate section than the one at the end (were Sister of Battle appears again for forgeworld units).

>DOES YOUR MODEL HAVE A DATASHEET IN A CODEX?
Yes, only Astra Militarum

>ARE THERE WARGEAR OPTIONS FOR YOUR MODEL THAT ONLY APPEAR IN THE INDEX VERSION OF ITS DATASHEET ?
Yes, Inferno Pistol.

>USE THE CODEX VERSION OF YOUR MODEL’S DATASHEET, BUT YOU CAN CHOOSE TO USE THE INDEX VERSION FOR ITS WARGEAR OPTIONS
>When coming to calculate the points cost, the Commissar himself and the bolt pistol have points in Codex: Astra Militarum, so you would use those alongside the cost for the power axe from Index: Imperium 2

So I use the priest datasheet and all point costs should come from Index Imperium 2 or it's updated value, which is 9pts in CA 2017.

The same way Codex Astra Militarum made the Priest bolt pistol now cost 1pts, the release of the Beta Codex without the priest literally have 0 impact on him and it's wargear cost.

I think the way GW is handling this is that they trash to push Munistorum Priest to be the Guard Preacher that can integrate in a guard detachement without breaking its bonus, while sisters of battle have access to cheaper options (that can't take wargear) because a single aura is better on 30 guards than 10 sisters.   

Anyway, priest should not be given ranged weapons if you aim to be competive (they come with krak grenades), at best a Maul. By taking a weapon you are handicapping yourself.
Hence, negotiate with your opponent that your army can be 2002pts instead of 2000 because of this rule fuckery -which is easier to convince him to accept than the cost really is 7pts when RAW it isn't-

**Comment by Dunamis55** [comment]
The problem, as I see it, is that CA2018 includes and/or replaces all of CA2017's updated points. However, the entire list of Adeptus Ministorum point changes have been removed from the Updated Point Values section, which I interpret as meaning for us to use the points listed in the Adeptus Sororitas Beta Codex for the Adeptus Ministorum. If so, then the Inferno pistol should be 7 points, not 9.

As a side note, personally, I'm not interested in what is or isn't competitive; only what is allowed and accurate in accordance with the rules. People can do whatever they want from that point onward.

**Comment by alphalas** [comment]
I honestly tend to agree with @nokhal on this one; and that seems to be the most logical progression to me.
