### ISSUE TITLE
Plague Marine Champion weapons

### ISSUE THREAD

**Issue by iamthesolo** [BSData/wh40k#5067]
**File/Catalogue:** 

**BattleScribe version:** 2.01.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.

Hi I've just realised Codex: Death Guard Plague Marine Champions using the Index option to select from the melee weapons list should also have the Balesword as an option just like how the CSM index HQs get a Thunder Hammer now.

Also the CSM Plague Marines are missing Index options.

Thank you

**Comment by Mad-Spy** [comment]
Thanks for letting me know that I'd made a mistake with the Index HQ options. They shouldn't have access to the thunder hammer as their equipment list hasn't changed.

Plague Champions can't take Baleswords at all. In the Index, they had to select from the _Champion Equipment_. There is no Champion Equipment list in the Death Guard Codex.

I haven't updated the CSM Plague Marines because no one has cared enough to complain about them.
