### ISSUE TITLE
Imperium - Space Marines: Units Missing Angels of Death

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5572]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.00

**Platform:** iPhone / iPod / iPad

**Dropbox:** Yes

**Description:** Hellblaster Squads, Redemptor Dreadnoughts, and Repulsors do not have “Angels of Death” listed in their rules.

**Comment by MrRWJP** [comment]
Not sure if this is the right way to do this, but the following units are also missing Angels of Death in addition to the units mentioned in the original report:

- Contemptor Dreadnought
- Dreadnought
- Ironclad Dreadnought
- Venerable Dreadnought
- Bike Squad
- Land Speeders
- Hunter
- Land Raider
- Land Raider Crusader
- Land Raider Redeemer
- Predator
- Repulsor Executioner
- Stalker
- Vindicator
- Whirlwind
- Stormhawk Interceptor
- Stormraven Gunship
- Stormtalon Gunship
- Drop Pod
- Land Speeder Storm
- Razorback
- Rhino

(Hope this is OK, thought it made sense to add to this related report rather than creating a new one.
