### ISSUE TITLE
Aeldari - Ynnari: Is it possible to remove the Ynnari warlord option?

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5732]
**File:** Aeldari - Ynnari.catz

**BattleScribe version:** 2.03.02

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** hi
thanks for reading ! :3

the yncarne, yvraine and the visarch have this weird "Ynnari Warlord" option that sometimes when selected unlocks ynnari psychic powers and relics for non-unique characters in the same detachment and sometimes when selected does nothing
we has a roster open right now with a < ynnari > unique character included and the "Ynnari Warlord" box ticked, but the other (non-unique) characters don't get to pick ynnari powers and relics still even though they could a couple of literal minutes ago.

it's bugged but that's not really the bug that needs fixing because there ought be another solution entirely that reworks the "Ynnari Warlord" tickbox into something else
because the way it works since the wd update to the ynnari rules as soon as one of the three unique ynnari characters is included in a detachment you can convert the detachment from a craftworlds, harlequins or drukhari detachment into a ynnari detachment instead replacing the keyword and then all non-unique characters that are part of that detachment get access to ynnari powers and relics. They can even be the warlord. You don't have to make yvraine, the visarch or the yncarne your warlord anymore;
they just have to be included in a detachment for you to be able to make that detachment ynnari and then another, non-unique character can be your ynnari warlord, if you like,
and every character in the detachment gets access to traits, powers, relics

thank you ! ^w^

**Comment by junglenights** [comment]
hi again !
update here :
we discovered that you can choose ynnari as a masque form under the force org slot heading, and this indeed allows you to choose ynnari traits, powers, relics for your nonunique ynnari characters ! ^w^

the ynnari warlord option has to be ticked to unlock the traits, but can be unticked afterwards without removing the trait (which is a neat way of simulating having chosen the warlord trait stratagem tbh :
1 - tick "ynnari warlord" on your warlord
2 - tick chosen warlord trait
3 - tick "ynnari warlord" on the character you want to have the warlord trait stratagem
4 - tick chosen warlord trait
5 - untick "ynnari warlord"
6 - stratlord still has the trait
nice !)

also this following may be a bug or maybe it's just an area for improvement :
you can't currently deselect the default weapon if you want to replace it with a relic, so in the roster it ends up listing both !
maybe instead have the default weapon disappear as soon as you select the replacement relic ?
also maybe recode it so that if the character doesn't have the default weapon already, the corresponding replacement relic options are greyed out and untickable ? that way eg only if you first choose to pay the points for a power weapon by ticking it, you will be able to replace it with the hungering blade by ticking that, which should then automatically replace the power weapon in the roster - might be a neater solution all in all !

thank you ! ^v^

**Comment by FarseerVeraenthis** [comment]
We'll have a look and see what we can do 😃

**Comment by FarseerVeraenthis** [comment]
yeah, this is definitely not working as anticipated...!

**Comment by FarseerVeraenthis** [comment]
this will be reviewed once the harlequins PA update has dropped. Then things will be stable... (hahaha! it's GW, who am I kidding!!)

**Comment by DrTobogganMD** [comment]
Combined into #8056 as a aeldari re-write is happening.
