### ISSUE TITLE
Imperium - Space Marines: Add Scions of Guilliman rule for UM

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#5931]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.06

**Platform:** Windows

**Dropbox:** No

**Description:** I think Ultramarines Scions of Guiliman is missing from the chapter rules

**Comment by WindstormSCR** [comment]
Because the supplement rule is contingent on having all units in the army be from a specific chapter, which is currently impossible to validate correctly

**Comment by LegioXV** [comment]
Hi. Maybe this can work? Having this selection rules description that any player can check in the game in better then having none. Maybe it can be checked by **Chapter Selection** to be Ultramarines or their successor Chapters and stated under Selection Rules the following way:

Scions of Guilliman: if you army is Battle-Forged and every unit in your army is Ultramarines (with the exception of Unaligned units), units in your army that has Combat Doctrines ability get this ability. <Ability description>

This should be pretty clear condition-based and easy to check by players. Because, to be honest, you can't either check if Detachment consists of units from the same faction, but we can assign CP for detachment as if it was
