### ISSUE TITLE
Space Marines - chapter specific litanies are not showing 

### ISSUE THREAD

**Issue by Dunamis55** [BSData/wh40k#6402]
**File/Catalogue:** Imperium - Space Marines v124

**BattleScribe version:** 2.03.16.325

**Platform:** Android

**Dropbox:** No

**Description:** Chaplain Cassius is unable to take the Ultramarines litany, March for Macragge, from Faith & Fury.

**Comment by acebaur** [comment]
He knows automatically in addition any he already knows. Same with the other chapter ones from F&F. At this point since it's something that isn't an option for them to take I'm not planning on adding it as we've had numerous reports of people having trouble with the catalog due to its size already. I will add them when we refactor SM in separate catalogs though.
