### ISSUE TITLE
SW - Infiltrators can't be Sgt 3 Infiltrators and Helix Adept

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6442]
**File:** Imperium - Space Wolves.catz

**BattleScribe version:** 2.03.10

**Platform:** Windows

**Dropbox:** No

**Description:** Infiltrators are allowed to have a squad comprised of a sergeant, 3 marines, and a helix adept. For the Space Wolves, one is stuck with 4 marines. One can't reduce the output to three and add a helix adept to meet the squad requirement. Every other space marine faction that uses this troop type can do this correctly, but the space wolves have a bug. Please, correct this.

**Comment by destonttanner** [comment]
New units have been released for the forces of
the Adeptus Astartes, and their datasheets can
be found in this update. Codex: Space Marines
describes how these units can be taken as part
of a Chapter from that publication, however
they are also available to many other Space
Marine Chapters. 
The following new units are available to the
Space Wolves: • Infiltrator Squad
Codex: This unit contains one sergeant and four infiltrators. It can additionally contain up to five infiltrators. It can contain one infiltrator helix adept INSTEAD of one infiltrator.
Please, read codex and correct thanks.

**Comment by alphalas** [comment]
@destonttanner yes that is exactly what the original bugrep says, and what I changed the name to. Thank you though
