### ISSUE TITLE
No Option For making Astra Militarum Roster ***#2

### ISSUE THREAD

**Issue by dheck175** [BSData/wh40k#6480]
**File/Catalogue:** 

**BattleScribe version:** 2.03.

**Platform:** Windows/iOS/Android/Mac/Linux

**Dropbox:** Yes/No

**Description:** Detailed issue description.
I made a post before asking for help but it was closed by someone before even making sure the problem was solved. It has not been solved so I will reiterate, when I open the options to create a roster there is no option for the Astra Militarum. The screenshot will perhaps better explain the situation. 
![Screenshot_20191225-144504](https://user-images.githubusercontent.com/59234920/71483132-5cb2e780-27d4-11ea-9c37-fe50128282d9.jpg)

**Comment by dheck175** [comment]
I have tried deleting and re-downloading the files but it did not fix the issue.

**Comment by alphalas** [comment]
The bugrep was closed because I cannot duplicate at all. So I’ll walk you through it.
![5DB413E4-60DD-4B19-B6A0-755F4410EDC9](https://user-images.githubusercontent.com/15703066/71483780-65f18380-27d7-11ea-8101-f688b671bfa4.jpeg)
First my attempt to duplicate.
![4967FF71-8AB4-4591-8F58-85E14D05582A](https://user-images.githubusercontent.com/15703066/71483796-786bbd00-27d7-11ea-9b49-d2260a9cee21.jpeg)
Click here
![7EF6EE72-7DAB-4B5F-9994-B234F1B025BF](https://user-images.githubusercontent.com/15703066/71483833-a51fd480-27d7-11ea-8f79-92a5e2c6022b.jpeg)
Then here.
![92194691-4B32-4BA5-A962-2E183909061A](https://user-images.githubusercontent.com/15703066/71483848-b79a0e00-27d7-11ea-856f-50b634ba1783.jpeg)
Then here. You’ll see this:
![92DBFAB3-8209-4FAD-B06A-91DDED431195](https://user-images.githubusercontent.com/15703066/71483877-d3051900-27d7-11ea-8899-d47106060dea.jpeg)
Make sure it looks like this before you hit ok:
![C5FE27BD-9B4F-4099-B66B-2EDB7F02E4E1](https://user-images.githubusercontent.com/15703066/71483907-e87a4300-27d7-11ea-9fc9-77181dc8c331.jpeg)

**Comment by dheck175** [comment]
OKay, thank you! I'll give that a shot.

**Comment by acebaur** [comment]
If that doesn't work try deleting the app and reinstalling

**Comment by dheck175** [comment]
It worked! Thank you for waiting for a response folks! I can now build my cadian force haha! Cheers!
