### ISSUE TITLE
Chaos - Dark Mechanicum: Knights should be removed from this catalogue

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6531]
**File:** Chaos - Questor Traitoris.catz

**BattleScribe version:** 2.03.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** Infernal Autosimulacra is missing for the Knight Acheron, and perhaps others, when taken in Chaos Knight detachments but still present in Dark Mechanicus detachments.

**Comment by Mad-Spy** [comment]
Those models no longer have that rule, since the Forgeworld Chaos Knights update from July.

https://www.warhammer-community.com/2019/07/25/more-knights-more-awesome-new-faq-and-update-now-livegw-homepage-post-2/

They should in fact be removed from that catalogue, as according to the datasheets in that link, they can no longer be given the DARK MECHANICUS keyword.

**Comment by Mad-Spy** [comment]
As there are now only two models in the Dark Mechanicus catalogue and they are both available to CSM, I'm retiring it. I'll mark it as a Library for the next release and remove it if we don't receive any complaints.
