### ISSUE TITLE
Imperium - Space Marines: IF/CF Relic validation is not working correctly.

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6557]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.03.11

**Platform:** Windows

**Dropbox:** No

**Description:** When I give a Character a Crimson Fists Relic, it tells me "[Character Name] has 1 too many selections from Relics of the Fists (maximum 0)." I have set **Chapter Selection** to "Crimson Fists" and to "Imperial Fists Successor." The Fist of Vengeance and Duty's Burden Relics should be Crimson Fists Relics, not Relics of the Fists.

Also, I can give Purgatorous to Characters that don't have bolt pistols or heavy bolts pistols, which should be impossible.

**Comment by Mad-Spy** [comment]
- Validation is not allowing Relics for CF characters (only to IF or Champion of Blades) 
- CF and IF Relics are not being correctly restricted to those chapters when Champion of Blades is not selected.
- The Spartean should be allowed for Heavy Bolt Pistol models, but is currently not.
- Duty's Burden is allowed for "bolt rifle" but its text in the supplement only allows it for auto and stalker. I can't find an Errata changing this.
- Purgatorus is not being correctly hidden due to using a Link in its conditions.

**Comment by acebaur** [comment]
Also I need to pull access for BT
