### ISSUE TITLE
Ravenwing Black Knights don’t have Corvus Hammer in their selections

### ISSUE THREAD

**Issue by jasarien** [BSData/wh40k#6579]
**File/Catalogue:**  
Imperium - Dark Angels.catz

**BattleScribe version:**  
2.03.09

**Platform:**  
iOS

**Dropbox:**  
Yes

**Description:**  
The codex specifies that any Black Knight can take a Corvus Hammer (not just the Huntmaster), but the options in Battlescribe don’t allow to select a Corvus Hammer on normal Black Knights, only the Huntmaster has it.

![A4C83070-245C-4B01-BFCA-AF0511306BF3](https://user-images.githubusercontent.com/104444/72227179-4b6a2900-3591-11ea-9389-fee57ff47542.jpeg)

![A25D2C71-3B44-40E7-AACA-06DD59253D5A](https://user-images.githubusercontent.com/104444/72227139-0219d980-3591-11ea-8d12-53d5e54c48a4.jpeg)

![4A6856AF-7FA0-4163-B5D4-00A2636E38BA](https://user-images.githubusercontent.com/104444/72227134-eb738280-3590-11ea-8979-5f2167ddcd48.jpeg)

**Comment by Thairne** [comment]
Cannot confirm on desktop

![grafik](https://user-images.githubusercontent.com/8590840/72243735-f78d2d80-35ec-11ea-9933-8883d7a763da.png)

Possible BS bug/outdated BS version .09?

**Comment by james-rantmedia** [comment]
Hm, my battlescribe says my Imperium - Dark Angels version is 122, and yours says 123. But nothing changes when I tell Battlescribe to update the data from the repo... advice?

**Comment by jasarien** [comment]
Hm, my battlescribe says my Imperium - Dark Angels version is 122, and yours says 123. But nothing changes when I tell Battlescribe to update the data from the repo... advice?

**Comment by Thairne** [comment]
That's because that option bloats the entry significantly. If you allow a Black Knight to not have a weapon, for whatever reason anyone ever would do this, you have to expand the selection to have each Black Knight individually so you can choose which one has a hammer and which one has not.
Since that option is absofuckenlutely useless, I opted for removing it to make the unit easier to handle.

if its broken on iOPS only however that smells like a BS bug...

**Comment by jasarien** [comment]
Ok, the reasoning for defaulting the selection makes sense, that's fine.

However, I don't know if it's just a Battlescribe iOS bug. When I render the roster in BS Desktop, I see the same output as the rendering from iOS where the normal Black Knights are just listed without their Corvus Hammer, so anyone looking at the roster that doesn't know they can have the hammers for free (and would take them by default) wouldn't know they're there.

<img width="1379" alt="Screenshot 2020-01-14 at 09 50 13" src="https://user-images.githubusercontent.com/104444/72333602-f7a43080-36b3-11ea-9004-d927b4e3c771.png">

**Comment by Thairne** [comment]
well that is interesting. That's the first time in like.. ever that I see the output actually differs from the selections in the app...
Still think it is a bug with BS itself, but lets see if v123 has the same issue since the hammers are no longer optional there.
Maybe BS screws up the output for the optional hammer for some weird reason...

**Comment by Thairne** [comment]
You dont happen to have minimal output turned on?

**Comment by jasarien** [comment]
Ha. Yeah. That was hidden under the "advanced options" menu. That fixes it on iOS as well. Thanks!
