### ISSUE TITLE
T'au MV1 Gun Drones equipped with 1 pulse carbine should be 2

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6667]
**File:** T'au Empire.catz

**BattleScribe version:** 2.03.17

**Platform:** Android

**Dropbox:** No

**Description:** According the the T'au Empire Codec ,on page 109, Gun Drones in the Tactical Drone Fast Attack section are equipped with two pulse carbines instead of one. I have not been able to find anywhere that has changed this.

Since I have you, great job. Keep up the excellent work!

**Comment by amis92** [comment]
They are equipped with 2 Pulse Carbines each.

You only see one profile; that's how it should be. The incorrect assumption is that because this equipment is non-modifiable, BattleScribe hides such entries in the default output settings (minimal).

To see Drones' weapons in the roster, please change Output from Minimal to different value.
