### ISSUE TITLE
Proposal: Move RSEs which are not truly "No Force Org Slot" to new categories

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#6733]
The "No Force Org Slot" Primary Category is becoming increasingly bloated as GW introduce new Stratagems and subfaction options.

Some authors have taken to prefixing their Stratagem entries to try and group them, but this doesn't really solve the problem.

My proposal is to create two new Primary Categories, "List Configuration" and "Stratagems".

List Configuration should contain any game type, faction selection, specialist detachments or similar entries.
Stratagems should contain only stratagems.
No Force Org Slot would then be left with only units which do not take up a slot.

This should improve discoverability of options for end users, who will no longer need to wade through possible irrelevant options to find No Force Org Slot units.

**Comment by Thairne** [comment]
Vote for creating a new category.
Strats that affect one single unit at the unit level e.g. "Veteran intercessors" should stay there for file size reasons as those types of stratagems might become more common in the future. Alternatively, if that is of no concern, those options might be hidden unless the corresponding stratagem is selected.

**Comment by Mad-Spy** [comment]
Decisions on how to implement individual Stratagems can be left up to the author. This would only affect Stratagems that either are (or would be) put into "No Force Org Slot".

**Comment by Mad-Spy** [comment]
@BSData/data-authors-wh40k, please read and comment.

**Comment by amis92** [comment]
I agree the current state of affairs is very much incorrect.

### Past

Let's go back to *why* there's even a thing called `No Force Org Slot` category: originally, it was meant for units that had rules stating that
> this unit does not take up a slot in a Detachment [...]

When we needed to add a single thing called "Game type" we considered creating new category for it but decided not to as it was just that one entry.

### Present

In time, we added more and more, treating it as "miscellaneous" category that contains anything not taking up a slot in detachments - and recently, that included Inquisition for most of Imperium, and an increasing number of Stratagems. Things are now mixed up and make it hard to find meta-information.

### Future

I'd like us to carefully reconsider the additional primary categories we want to instantiate, and their names.

* No Force Org slot (NFO) is definitely needed, but should go back to it's original function.

* Configuration is also something that should be separated - but here I'd like to select a better name; we definitely have a couple of entries to put here, e.g. Game type, Chapter/subfaction selection, detachment CPs, special detachment selections etc.; my ideas: Meta, Configuration, Properties, Setup. Also let's keep in mind that these entries will be selected in every detachment (for detachment CP or subfaction selection) - so List Configuration would appear to apply to the whole List/roster.

* Stratagems are definitely a good name for stratagem-containing category; there were also suggestions it should be "CP stuff" category, so that we get detachment CPs thrown in as well; then it'd need a different name

**Comment by GenWilhelm** [comment]
Fully agree with this. It should also make the output a little more organised when you have lots of non-unit selections.

Where would reference selections go? (I.e. selections that are just quoting relevant rules, rather changing how the list is built)

**Comment by WindstormSCR** [comment]
Configuration: anything that affects the detachment such as faction selectors, game type, etc. It communicates the purpose of the category without being too narrow.
Stratagems/Reference: not sure what separating character would need to be used, but this makes it clear the listed things are there to show rules or items that are in use, but not a unit.
No Force Org: Units that do not occupy a FO slot, in step with GW's own wording.

**Comment by DrTobogganMD** [comment]
I'm all in favor of these 3. I can easily maneuver my cats into their usage.

**Comment by amis92** [comment]
> Stratagems/Reference: not sure what separating character would need to be used, but this makes it clear the listed things are there to show rules or items that are in use, but not a unit.

I don't think Stratagems should contain anything other than them.

> Where would reference selections go? (I.e. selections that are just quoting relevant rules, rather changing how the list is built)

I'd just place that in Configuration as well. Those are switches, aren't they?

**Comment by amis92** [comment]
Also, what do you think about calling the category

### Pre-battle stratagems

**Comment by Mad-Spy** [comment]
I feel just **Stratagems** is sufficient, and more concise. "When everything is a Pre-battle stratagem, nothing is" 😄

**Comment by amis92** [comment]
Well my reasoning is, if we give Stratagems category, people might start complaining "these are not all strats, just pre-battle ones" 🤷‍♂️

But yeah, KISS so I'm also for just Stratagems

**Comment by FarseerVeraenthis** [comment]
sounds good to me, when are we planning on "green lighting" the decision and impementing it into the project??

**Comment by Mad-Spy** [comment]
I've done the groundwork for this, https://github.com/BSData/wh40k/pull/6744

If people can review, I am happy to work through the other catalogues.

**Comment by DrTobogganMD** [comment]
At work so I cannot, but I trust ya :p I'll convert my cats tonight then

**Comment by amis92** [comment]
@DrTobogganMD I think it'd be better done in a single sweep (if @Mad-Spy can do that in terms of capacity).

**Comment by DrTobogganMD** [comment]
Works for me!

**Comment by Mad-Spy** [comment]
This work has been merged. I think I got all of the changes, but please check your catalogues.

**Comment by amis92** [comment]
edited title for better searchability in future
