### ISSUE TITLE
Imperium - Blood Angels: Astorath Litany profile is incorrect

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#6830]
**File:** Imperium - Blood Angels.catz

**BattleScribe version:** 2.03.12

**Platform:** Windows

**Dropbox:** No

**Description:** Astrorath no longer has the Litanies of Hate special rule. Just the Litany of Hate litany that goes off on a 3+

**Comment by alphalas** [comment]
![0C1FEEBC-FD41-4E6D-B675-F0087727F6D6](https://user-images.githubusercontent.com/15703066/75727203-5ea49580-5cb2-11ea-8279-3d40ef896bb3.png)
![A494283B-0499-4A43-9A63-7EC6ECE80F80](https://user-images.githubusercontent.com/15703066/75727204-5f3d2c00-5cb2-11ea-8360-b0a85d94eb8a.png)

So while it is double linked and I’ll have to remove one of them, he is otherwise correct
