### ISSUE TITLE
Imperium - Blood Angels - Honoured by Baal doesn't work.

### ISSUE THREAD

**Issue by cwoac** [BSData/wh40k#6867]
**File/Catalogue:** Imperium - Blood Angels
**BattleScribe version:** 2.03.
**Platform:** Windows/Android
**Dropbox:** No
**Description:** 
Previous fix to add 'honoured by baal' (#6777) adds it, but it doesn't work.
Steps to reproduce:
* Create new roster using Imperium/BA
* Select BA successor (I used Lamentors)
* Add Strategy 'Honoured by Baal'
* Add unamed character + make warlord.

Character _should_ now have access to relics of baal, but only has special issue wargear.

**Comment by Mad-Spy** [comment]
![image](https://user-images.githubusercontent.com/29306451/76307254-666ec600-62c0-11ea-9e78-ac8faddd1548.png)

**Comment by Mad-Spy** [comment]
@cwoac, you have to drill-down into Warlord and check "Honoured by Baal" on the model you want to have the BA Relic. That will then unlock them.

**Comment by Mad-Spy** [comment]
@alphalas, you have Honoured By Baal linked to Root as well as in the Warlord selection. This means that people will pay twice for the same thing, probably by accident. It might be better from a UX perspective to move Honoured by Baal to the root of the model, rather than nesting it in Warlord?

**Comment by cwoac** [comment]
@Mad-Spy  - Noted, thanks.
I will leave this open though for alphalas to consider the question you raised / close as appropriate.
Also, it raises the question of why it was added to the strategems section if that has no effect?

**Comment by Mad-Spy** [comment]
I've moved Honoured by Baal to the root of all eligible models (rather than nesting it in Warlord) and updated the modifiers to make it hidden until you take a Warlord. I've also removed the erroneous link in the Root Selection Entries.

I've also updated the modifiers for "Hero of the Chapter" to do the same (hide it when there's not a Warlord in the Roster, or if a model is the Warlord).
