### ISSUE TITLE
Some Tau PA fixes

### ISSUE THREAD

**Issue by joarangoe** [BSData/wh40k#6875]
**File/Catalogue:** Tau
**BattleScribe version:** 2.03.12
**Platform:** Windows
**Dropbox:** No
**Description:**

Hello.

Here are some fixes for the post PA data:

- Coldstar has LEGENDARY UNIT keyword, which is not.
- Riptide shows option for High-powered incinerator and reactive countermeasures, which it cant have (due to not being able to equip flamers or an airbursting frag projector).

**Comment by Mad-Spy** [comment]
The options show for the Riptide but will give a validation error if you select them. It's not the most intuitive UX but that's up to @amis92.

However, Prototype Weapon Systems visibility is incorrect. They are currently visible whether or not there is a Warlord in the Roster, due to having a "Set Hidden to False" modifier but the SSEG itself is not hidden.

**Comment by Mad-Spy** [comment]
I've fixed the visibility issue. I'm not sure whether "Legendary Unit" is being used to trigger some functionality, so I've left that for now.
