### ISSUE TITLE
Imperium - Blood Angels - wrong max count for dev sergeant weapons

### ISSUE THREAD

**Issue by MWGNZ** [BSData/wh40k#735]
**File/Catalogue:** 
Imperium - Blood Angels.catz v12
**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** According to the index a devastator sergeant can choose to swap his boltgun for weapons from the sergeant equipment list. This includes a section that starts "Up to two weapons can be chosen from the following list" and includes the normal things like pistols and chainswords. If you try and select more than 1 weapon from this list in battlescribe you get a validation error of "Space Marine Sergeant has 1 too many selections from Sergeant equipment (maximum 1)".

Validation of the equipment list is working fine for tactical squads so may be able to be copied from there.

**Comment by GenWilhelm** [comment]
The problem is the devestator sergeant has a bolt pistol that he can't replace, so he already has 1 selection from the first list by default. However, he should be able to pick one weapon from each list (in addition to his bolt pistol), but it looks like this currently isn't the case in the Blood Angels catalogue.
