### ISSUE TITLE
All Factions - Under-strength Units

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#780]
OP:
> ## **Description:** I cannot include under-strength units in the roster

Let's discuss. Propositions how to do that, how viable it is, prototypes, anything on topic is welcome.

You can vote or manifest your feelings with reactions (upper right corner of this post)

---

~**File:** Necrons.catz~

~**BattleScribe version:** 2.01.03~

~**Platform:** Windows~

~**Dropbox:** No~

~**Description:** I cannot include under-strength units in the roster~

**Comment by Kohato** [comment]
I didn't include that because that kind of cheese makes even 7th ed scatbikes look fresh.  We're still deciding if we want to do this as it causes all sorts of issues.

**Comment by amis92** [comment]
*And* is insanely complicated (for a feature that is so extremely rare by design).

**Comment by Kohato** [comment]
This will stay open for discussion for now, but I won't be implementing it as of yet.

**Comment by amis92** [comment]
Let's raise it as a global thing.

**Comment by Crowbar90** [comment]
I'm planning on trying to implement it on Blood Angels. Since it's a pretty rare feature, my idea is to include a "dummy" entry called "Allow under-strength" in No Force Org, which unhides a "Under-strength" choice inside every unit. Choosing it would lift the min size requirement. I'll still have to check the "1 per army", but I think it can be done.

**Comment by USSX-Hares** [comment]
And do not forget that no more than 1 such unit can be included per army

**Comment by amis92** [comment]
Since we now know (per [new FAQ v1.1](https://17890-presscdn-0-51-pagely.netdna-ssl.com/wp-content/uploads/2017/07/40K_8th_ed_Update_Rulebook_ver_1.1.pdf)) you can only have USU (Under-Strength Unit) in Auxiliary Detachment (in matched play), I have a new idea:

Let's make a special entry with an entry group of min/max1 of all army's choices AND in that same entry just throw in an entry called `[UNDERSTRENGTH PAYBACK]` with an adjustable points value (negative).

Or we fix this globally by adding a new Force Type "Aux. Sup. Detachment [UNDERSTRENGTH]" which will be a copy of current one BUT with a category like that entry above (understrength payback) that has single entry from gst - the entry like above.

I may not have been very clear, please ask and discuss.

**Comment by GenWilhelm** [comment]
Why not implement it like Blood Angels where adding the `[UNDERSTRENGTH]` entry removes the minimum size of the squad, but sets the unit to max 1 in roster.

**Comment by amis92** [comment]
Well because you can only now do that in Aux. Detachment legally.

Besides, it's a lot of work to set it up like that, and solving it globally is nice and clean. Output may not be pretty, but it probably won't be overused now, as it costs you CPs. So now we have a modest solution to a rare need. Appropriate if you ask me.

**Comment by GenWilhelm** [comment]
Make the `[UNDERSTRENGTH]` entry hidden unless its in an Aux. Support Detachment?

How would I represent how many models each of my understrength units are taking? And how would the payback entry know how many point to refund?

**Comment by FarseerVeraenthis** [comment]
Why not just add a modifier to the minimum requirement for each unit that is only switched on in an Aux detachment? You can only take one unit in that detachment anyway, the only thing to figure out is how to validate the unit type across the roster

**Comment by flakpanda** [comment]
Doing this either way kinda sucks imo. I would be adding 2 or 3 things to each node in the tree... thats a lot of bloat for a very specific this now.

**Comment by Thairne** [comment]
I guess we can conclude that we're not doing it?
There seems to be no real need for it anyway, considering user requests...

**Comment by GenWilhelm** [comment]
Seems to me like it would be a whole lot of effort, that just adds extra bloat, for very little return.

**Comment by amis92** [comment]
Agreed.
