### ISSUE TITLE
Imperium - FW Death Korps of Krieg Death Rider Command Squadron Wrong Points

### ISSUE THREAD

**Issue by gothmogbalrog** [BSData/wh40k#781]
**File/Catalogue:** 
FW Death Korps of Krieg v4
**BattleScribe version:** 2.01.

**Platform:** Windows

**Dropbox:** Yes/No

**Description:** The Death Rider Command Squad is double charging for the models in the unit. Seems that the Squad costs 60 points (15 per model) and then it is still charging points for each model (so another 60) so you are ending up 120. Then it is only charging for 1 lance per squad (2 points), when it should be 2 per model (so 8). Cost total should be 68. Right now it is charging 122.

**Comment by jShepherddog** [comment]
one more issue I'm finding is the Death Korps of Krieg Command Squad, the Standard Bearer needs to be 7pts instead of 0pts other wise you are not paying the base cost of the veteran and only paying for the banner.

![image](https://user-images.githubusercontent.com/30080443/28181263-f97ee2a6-67d5-11e7-8a3d-b898e132b76d.png)

**Comment by CrusherJoe** [comment]
Okay got those both fixed up in v5 of the catalog! Thanks for reporting!
