### ISSUE TITLE
Imperium - Grey Knights - Brother Captain Stern

### ISSUE THREAD

**Issue by nairul** [BSData/wh40k#840]
**File/Catalogue:** Grey Knights v5

**BattleScribe version:** 2.01.03

**Platform:** ...yes

**Dropbox:** No

**Description:** 

- [ ] Brother-Captain Stern should only be able to select one psychic power
- [ ] Brother-Captain Stern should only be allowed to take a force sword and no other melee weapon

**Comment by tekton** [comment]
Can you please update your data file to at least Grey Knights v5? I fixed that a while ago, but if you're still getting it after updating data please let us know.

Also, there's a basic format for bugs/reports to fill out that makes this easier to track down in the long run- to save me from being stupid and answering incorrectly it's best to use that :)

**Comment by nairul** [comment]
Sorry, next time I'll use the proper format for reporting bugs.

I've just updated data and am still seeing these errors on Stern. It says I'm using Grey Knights v5. Is there a newer version for Grey Knights data? If so, might you know why I'm not updating correctly?

**Comment by tekton** [comment]
If you make a new army is it still happening? I just tried on fresh installs in Windows, OSX, iOS and Android and it seemed good; just trying to take out possible issues.

If your army is based on an older version it's possible it's still using his old stats which were indeed wrong due to a copy/paste fail- but that was quite a few versions ago.

Which system are you having the issue on? Are you able to get a screen shot of it still happening?

**Comment by nairul** [comment]
I'm on Windows 10. Just uninstalled Battlescribe and reinstalled to version 2.01.03. Just deleted all data and  added Warhammer 40,000 8th Edition v17. Created a new roster, Imperium - Grey Knights v5.

![image](https://user-images.githubusercontent.com/24702032/28298228-174f83f4-6b40-11e7-91df-6a2d16ae4a0d.png)

**Comment by tekton** [comment]
Now I see the problem, I was reading your comment backwards; in the future I would suggest things like: 

• Stern should only be able to chose one power, he can currently select two

That gives a bit of clarity for the people reviewing it since we go through a lot of stuff. That combined with the normal bug layout and we should be able to get through these quicker.

Thanks for finding another one!

**Comment by nairul** [comment]
Ah -- sorry I was unclear! Thanks for your hard work.
