### ISSUE TITLE
Imperium - Space Marines - Dev Sarge selection validation bugged

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#872]
**File:** Imperium - Space Marines.catz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Devastator Sergeant has bolt pistol and boltgun, he can trade only boltgun for only one item from Sergeant Equipment list. Yet BS allows me to again select ie. boltgun and chainsword in addition to non-tradable bolt pistol.

**Comment by GenWilhelm** [comment]
By giving up his default boltgun, the Devastator Sergeant has free reign to take items from the sergeant equipment list, so long as he does not take more than two weapons from the first half, or more than one from the second half. Since his mandatory bolt pistol is in the first half, he may take one additional item from the first, and one item from the second half.
