### ISSUE TITLE
Imperium - FW Death Korps of Krieg: Grenadier weapon team incorrect cost and max unit size

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#895]
**File:** Imperium - FW Death Korps of Krieg.catz

**BattleScribe version:** 2.01.05

**Platform:** Android

**Dropbox:** No

**Description:** Grenadier Weapons Team points cost and unit model count do not accurately calculate or represent their being formed by 2 Grenadiers. The Grenadier Weapons Team currently only costs 17 points - that of the Heavy Flamer on its own without the 2 Grenadiers carrying it. Also, a unit that should be legal - Weapons Team, 2 Grenadiers with Special Weapons, Watch Master, and 5 Grenadiers - is being reported as 1 model too large.

**Comment by shadaras** [comment]
Also, the regular Grenadiers can be changed from individually added entries in the unit, to a numbered selection by unticking the "Shared?" boxes on their Hot-Shot Lasguns. I think this also applies to the Engineers squad, too.

That will neaten up the unit entry in both the editor and saved roster, without having 5-9 lines of "Death Korps Grenadier - Hot-Shot Lasgun". You'll instead get one line eg. "6x Death Korps Grenadier",  and they will still be costed for their equipment as appropriate.

Likewise you could move the Frag & Krak Grenade entries into the individual model entries, untick their Shared boxes, and have them included in the unit by default instead of having a numbered selection for them.

I'd do this all myself except I'm stuck on a phone for the next few hours.

**Comment by alphalas** [comment]
@shadaras that's not quite how it works, but you're about halfway there ;)
