### ISSUE TITLE
Chaos - CSM - Problems Uploading Files

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/wh40k#931]
**File:** Warhammer 40,000 8th Edition.gstz

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** Yes

**Description:** Hi i fixed some errors in chaos space marine, i try to submit th file but i can't do for an error. Your system to update data file deleted two times my corrected file .catz so i think that this problem should be corrected.

**Comment by ilaunchbury** [comment]
Thanks for having a go at editing the files. How are you submitting your corrected file? Are you using GitHub desktop?

What errors did you fix? I've fixed a number of things in the latest update (which hasn't made it to AppSpot yet).

**Comment by amis92** [comment]
I think Anon uses AppSpot. That feature isn't working since some time [uploading files there].

**Comment by FarseerVeraenthis** [comment]
Please join us on Gitter to discuss any problems you might be having: https://gitter.im/BSData/wh40k

Also, you should use github to upload .cat files to the repo, there are several access requirements that have to be met before "just anyone" can upload / edit files in order to stop wholesale chaos. 
The .catz files are compressed versions that are used by the roster building app.
