### ISSUE TITLE
Blood Angels Assault squad issues

### ISSUE THREAD

**Issue by ilaunchbury** [BSData/wh40k#959]
**File/Catalogue:** Blood Angels v16

**BattleScribe version:** 2.01.03

**Platform:** Windows

**Dropbox:** No

**Description:** 

- Assault Marine Sergeant should be min 1, currently you can deselect him.
- Why is a Marine w/ Eviscerator not a "Weapon upgrade"?
- The weapon options for the Sergeant seems to be causing problems for people (there have been 4 tickets raised about it). The layout in the main SM catalogue appears to be a better solution, perhaps it could be copied?

**Comment by Crowbar90** [comment]
- Doesn't removing the sergeant raise a validation error? I'll have to check the constraints.
- Because there are different constraint between eviscerator and other weapons. It was simply easier to set it up that way.
- You're right about that, unfortunately this was the first squad I added to the catalogue before the SM one even existed, so I couldn't copy anything. I'll make sure to look at it and update BA though.
