### ISSUE TITLE
Thoughts about subfactions and duplication

### ISSUE THREAD

**Issue by Mad-Spy** [BSData/wh40k#967]
I mentioned in gitter the other day about how it would be nice if we could have "sub-GSTs" which would allow units which are common to multiple armies to have a single record, instead of having to update them multiple times for every change and make sure everything is in sync.

This led me to thinking whether it would be practical to change up CSM to have a main catalogue which contains all the shared units, and have the sub-faction cats **only** include the listings for a particular subfaction.  Users could then add them as a child force to the main catalogue and the main catalogue could then update itself via "hidden" modifiers to only show valid models for the sub-faction.

The concept works in principle, but would it be too much to ask users to do this? Users of FW models already have to do it to get those models included, but obviously that is a limited subset of all the people who use BS.

Comments and thoughts are welcome.

**Comment by amis92** [comment]
First of all, our priority would be to convince @Jonskichov that catalogue imports are needed, *badly*. Second step would be to ask Jon how long will it take to implement it. Next, wait. And then, implement.

There is of course another way, which you propose here, and that is what we'll have to fallback to in case the above person doesn't intervene timely ;)

As to your suggestion, I believe it not to be good for the following reasons:
* dividing factions into separate catalogues was meant as a solution to over-bloated catalogues. Your solution essentially renders that invalid.
* hiding units, be it for this or any other purpose, is very much unadvised if we care about UX; also it's one of more bugged BS features *and* takes quite a lot of processing power (from team experience)
* Changing MFDs (Multi-Faction Detachments) to another setup will *definitely* cause a lot of problems - but I have to admit I'm not exactly sure how different the setup would be per your architecture.

This is not to say your idea is just bad. Obviously it will be more maintainable, which in case of Chaos is very much wanted I guess; but you've already covered why it's good, so. :)

**Comment by cartag** [comment]
Would you suggest doing this for all of the imperium then? Have one SM cat with sub ones for DA, BA, SW, etc? The armies that are unique enough to have their own army list are likely the ones that will have their own coders sooner rather than later. If you think your minor inconvenience of updating a rhino in three files is bad, wait until you have to do show/hides for implementing something like Traitor Legions. Having all in one is an absolute nightmare, I say that from first hand knowledge.

**Comment by FarseerVeraenthis** [comment]
Also, child detachments in BS can be bugged where the costs of wargear items doesn't update itself properly...
I'm not sure if this has been fixed in recent releases of BS, but that would make me wary of forcing users to ALWAYS use child detachements for some armies...

**Comment by alphalas** [comment]
At this point in time, I think it's fair to say it's a no-go, soz.

**Comment by Jonskichov** [comment]
Hey guys,

@amis92 DM'd me on Twitter and highlighted this discussion to me (thanks!). Unfortunately I was blessed by Father Nurgle over the last week or so and frankly have been pretty rough, so apologies for not getting back sooner.

Anyway, long story short, the foundations for combining catalogues was laid in 2.0 with the way game system data is merged into catalogues. I should be able to leverage this and extend it to combining catalogues too - this was always the plan. We should be in a good position to get this going fairly easily.

If you guys are keen, then I'll start working on this now as the next major update (2.02).

There are details to work out. As I remember, there was talk of this a long time ago during the 1.x days that got rather complicated with a bunch of pitfalls coming to light. It got abandoned.

With 2.0, I think we are in a better place, but details still need to be worked out.

One possibility would be a hierarchical system, where a catalogue "extends" some parent catalogue (which in turn can extend further catalogues...) much like inheritance in programming (if you're familiar with that). Basically the same as the catalogue -> game system relationship currently stands, except you could have a "chain" of catalogues - a catalogue would mark one (and only one) "parent" catalogue that it draws from.

Another possibility would be more of an "import" system, where the game system and some number of catalogues would just all be merged together into one big blob. In this scenario, a catalogue would specify zero or more other catalogues that get merged in (imported) and combined to make the final product.

Or, you know, both of these. I'm very much thinking aloud here so I'm happy to hear suggestions too.

Word of warning though, this won't be a quick update. While the internal gubbinz shouldn't need too much work, there are significant UI changes that would need to be done to support it - in Data Editor, in the mobile and desktop versions of Roster Editor. This is going to need to go through beta.

**Comment by ilaunchbury** [comment]
Thanks for taking the time to respond, @Jonskichov.

My initial thoughts were to have a hierarchical system, so we could have a "WH40K" gst, then a Faction-level catalogue with common units and wargear, then a "Army" catalogue with army-specific units and rules. Each lower level would be linked upwards to a single higher-level item, but all the items in the higher levels are available at the lowest level in the data editor. The mid-level items could be invisible to the end user in the roster builder (as they only need to know which game system and army they are choosing).

If this is something that's a possibility, then that is great.

**Comment by amis92** [comment]
I believe we should try to support the "import" system first and only if that fails, fall back to "hierarchical". Why?

* It's simply more universal. We as 40k might be okay with just a hierarchy; what about others?
* It's probably useful for us too: Forge World. Where in hierarchy would it be? In my eyes it always is a side dish. 🍽 
* More loose coupling. Always poses challenges for implementer but makes life so much easier for development at large.

Do we continue discussion here, or move it to BattleScribe repo?

Next step would be finding and resolving challenges posed by import/multi-inheritance system. The most obvious is the diamond problem. (For non-programmers https://en.wikipedia.org/wiki/Multiple_inheritance#The_diamond_problem)

```
    A
 /      \
B      C
 \      /
    D
```

So D is game system,
C is Codex catalogue and B is Forge World catalogue.
A would be a Faction catalogue.

What issues can that pose? If imports are "integrated" so for a Bolter profile defined in D(gst) it would be seen as defined in B and C, it creates "duplicate" same-id profiles imported into A. Which one is imported?

The solution would be not to "integrate" these items on such a low level but rather reference them as "import from D", and then in A we have two "imports from D of Bolter profile" which will simply be resolved as a single import.

Another possible decision to take is how granular should imports be, and what should they *import* by default. In my opinion, KISS (Keep It Simple Stupid). Single item level granularity will be very complicated and probably create more issues than solve. So rather than that, just take everything in.  *Everything* is however debatable. Shared items are obviously in that set, but should Selection Entries/Links be too?

**Comment by ilaunchbury** [comment]
>It's probably useful for us too: Forge World. Where in hierarchy would it be? In my eyes it always is a side dish. :plate_with_cutlery:

 I was thinking that FW would be a separate hierarchy (the mid-level catalogue would be optional, so it would just go GST->FW cat, as it does now) and you would continue to create multi-catalogue detachments. That avoids the diamond problem as each catalogue would only have a single parent (whether that parent is a GST or another CAT).

>What issues can that pose? If imports are "integrated" so for a Bolter profile defined in D(gst) it would be seen as defined in B and C, it creates "duplicate" same-id profiles imported into A. Which one is imported?

De-duplicating imported ids *should* be relatively simple, as you can just discard one if the ids match when doing the import (and only when doing an import).

>Another possible decision to take is how granular should imports be, and what should they import by default. In my opinion, KISS (Keep It Simple Stupid). Single item level granularity will be very complicated and probably create more issues than solve. So rather than that, just take everything in. Everything is however debatable. Shared items are obviously in that set, but should Selection Entries/Links be too?

As I've said before, my thoughts are that the new level of file is like a mini-GST. For example, all SM armies have Tactical Marines, so their shared selection entry goes into the new level, but their root selection entry goes in the bottom level.

**Comment by GenWilhelm** [comment]
I agree that we should keep it as simple as possible. I think it's best done by simply allowing a Catalogue to import from one or more Catalogues in the same manner as the GST, excluding any Root Selection Entries. In addition, a Catalogue should be able to be hidden from the force selection menu, so that we can have "abstract" Catalogues that just hold shared information for multiple top-level Catalogues, without being a complete Catalogue in them self.

**Comment by amis92** [comment]
>>It's probably useful for us too: Forge World. Where in hierarchy would it be? In my eyes it always is a side dish. :plate_with_cutlery:
>
 >I was thinking that FW would be a separate hierarchy (the mid-level catalogue would be optional, so it would just go GST->FW cat, as it does now) and users would continue to create multi-catalogue detachments. That avoids the diamond problem as each catalogue would only have a single parent (whether that parent is a GST or another CAT).

Maybe a better example would be The Fallen, as they are cross-Top-Faction shared and yet have their Factions (contrary to Unaligned units like Fortifications).

**Comment by GenWilhelm** [comment]
Don't forget we have Ynnari to deal with. Craftworlds, Drukhari, and Harlequins need to be individually maintainable, but ideally the Ynnari Catalogue should inherit from all of them.

**Comment by amis92** [comment]
I've remembered another important thing. We'll probably want to mark some catalogues as hidden, maybe implicitly by not having any non-shared selection entries/links or explicitly through some attribute.

Such catalogues would only be used as imports and never selectable in Roster Editor. They'd be like libraries of common stuff.

**Comment by capitaladot** [comment]
I really like @Jon's second proposal, which I understand as file side, data editor implemented file includes, with one caveat: any imported entities (entries,  rules, profiles) would need to be mutable with modifiers.

This would be a feature improvement/addition to how imported entities from the GST work, which are presently immutable (and it would be great to have these made mutable as part of this workset).

**Comment by amis92** [comment]
@capitaladot could you give an example of use case that would not be doable by other means?

**Comment by capitaladot** [comment]
@amis92 as a data editor, I find it necessary to alias some special rules from the GST that are included under a different heading than the named special rule conferred.

The current workflow does not allow modifiers on Rules linked to Selection in CATs, and requires making a copy of the linked GST rule into the CAT.

This is undesirable because it breaks the linkage from Rule in the GST and leaves us to maintain two rules by value instead of one rule by reference.

**Comment by amis92** [comment]
> The current workflow does not allow modifiers on Rules linked to Selection in CATs, and requires making a copy of the linked GST rule into the CAT.

I think we should search for another solution here. Allowing modifiers on imported items has many undesirable implications and definitely will prove harder to be implemented, thus lowering chances of it happening.

I'd propose enabling modifiers to reference arbitrary GUIDs, and it would enable the scenario you require (so modify on condition pertaining to some entry from catalogue not imported but rather importing). If the ID is not found on runtime, the condition/modifier simply isn't activated.

How'd you feel about that?

**Comment by FarseerVeraenthis** [comment]
I'd love to have an opinion, but I am feeling a little out of my depth... I support anything that reduces duplication and simplifies maintenance, however you get there is up to you, largely because I don't understand the programming required to implement any of the suggestions proposed so far...

**Comment by capitaladot** [comment]
@amis92 yes, I think that is what I am asking for; I don't intend to suggest actually changing the GST entry per se, but to be able to have modifiers act against the GUID-associated linked copy. This avoids the current workflow, wherein the editor enables (and requires) having to make a by-value copy that loses its linkage to its source in the GST.

**Comment by WindstormSCR** [comment]
The Import function would be considerably more flexible and would enable easier handling of variant rulesets within the same Edition of a game system (the "Imperial Agents" problem)

**Comment by capitaladot** [comment]
Still needed, should not have been closed without comment.

**Comment by WindstormSCR** [comment]
@capitaladot things that are lengthy discussions are getting the discussion tag for easy location without clogging up the current bug queue, and this is stalled for now until import/inheritance becomes a feature

**Comment by capitaladot** [comment]
This was a place to work out how we want the feature to work.

A cluttered, transient and ephemeral by nature Gitter stream is no place
for persisting those thoughts to share with @Jonskichov

**Comment by alphalas** [comment]
@capitaladot yes, but it’s not like it’s deleted, it’s just closed. All you need to do is sort by tags and it’ll be simple to find.

**Comment by amis92** [comment]
For all we know, this can be resolved next month or next year. It's not really active. And it's definitely not an actual issue for 40k.
